steps:
- name: 'gcr.io/cloud-builders/bazel'
  entrypoint: bazel
  args: ['test', '--test_output=errors', '...']
  id: bazel-test
  waitFor: ['-']
timeout: 15m
options:
  machineType: 'N1_HIGHCPU_32'
