// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.27.1
// source: cel/expr/conformance/proto2/test_all_types_extensions.proto

package proto2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Proto2ExtensionScopedMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Proto2ExtensionScopedMessage) Reset() {
	*x = Proto2ExtensionScopedMessage{}
	mi := &file_cel_expr_conformance_proto2_test_all_types_extensions_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Proto2ExtensionScopedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Proto2ExtensionScopedMessage) ProtoMessage() {}

func (x *Proto2ExtensionScopedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_cel_expr_conformance_proto2_test_all_types_extensions_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Proto2ExtensionScopedMessage.ProtoReflect.Descriptor instead.
func (*Proto2ExtensionScopedMessage) Descriptor() ([]byte, []int) {
	return file_cel_expr_conformance_proto2_test_all_types_extensions_proto_rawDescGZIP(), []int{0}
}

var file_cel_expr_conformance_proto2_test_all_types_extensions_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*TestAllTypes)(nil),
		ExtensionType: (*int32)(nil),
		Field:         1000,
		Name:          "cel.expr.conformance.proto2.int32_ext",
		Tag:           "varint,1000,opt,name=int32_ext",
		Filename:      "cel/expr/conformance/proto2/test_all_types_extensions.proto",
	},
	{
		ExtendedType:  (*TestAllTypes)(nil),
		ExtensionType: (*TestAllTypes)(nil),
		Field:         1001,
		Name:          "cel.expr.conformance.proto2.nested_ext",
		Tag:           "bytes,1001,opt,name=nested_ext",
		Filename:      "cel/expr/conformance/proto2/test_all_types_extensions.proto",
	},
	{
		ExtendedType:  (*TestAllTypes)(nil),
		ExtensionType: (*TestAllTypes)(nil),
		Field:         1002,
		Name:          "cel.expr.conformance.proto2.test_all_types_ext",
		Tag:           "bytes,1002,opt,name=test_all_types_ext",
		Filename:      "cel/expr/conformance/proto2/test_all_types_extensions.proto",
	},
	{
		ExtendedType:  (*TestAllTypes)(nil),
		ExtensionType: (*TestAllTypes_NestedEnum)(nil),
		Field:         1003,
		Name:          "cel.expr.conformance.proto2.nested_enum_ext",
		Tag:           "varint,1003,opt,name=nested_enum_ext,enum=cel.expr.conformance.proto2.TestAllTypes_NestedEnum",
		Filename:      "cel/expr/conformance/proto2/test_all_types_extensions.proto",
	},
	{
		ExtendedType:  (*TestAllTypes)(nil),
		ExtensionType: ([]*TestAllTypes)(nil),
		Field:         1004,
		Name:          "cel.expr.conformance.proto2.repeated_test_all_types",
		Tag:           "bytes,1004,rep,name=repeated_test_all_types",
		Filename:      "cel/expr/conformance/proto2/test_all_types_extensions.proto",
	},
	{
		ExtendedType:  (*TestAllTypes)(nil),
		ExtensionType: (*int64)(nil),
		Field:         1005,
		Name:          "cel.expr.conformance.proto2.Proto2ExtensionScopedMessage.int64_ext",
		Tag:           "varint,1005,opt,name=int64_ext",
		Filename:      "cel/expr/conformance/proto2/test_all_types_extensions.proto",
	},
	{
		ExtendedType:  (*TestAllTypes)(nil),
		ExtensionType: (*TestAllTypes)(nil),
		Field:         1006,
		Name:          "cel.expr.conformance.proto2.Proto2ExtensionScopedMessage.message_scoped_nested_ext",
		Tag:           "bytes,1006,opt,name=message_scoped_nested_ext",
		Filename:      "cel/expr/conformance/proto2/test_all_types_extensions.proto",
	},
	{
		ExtendedType:  (*TestAllTypes)(nil),
		ExtensionType: (*TestAllTypes_NestedEnum)(nil),
		Field:         1007,
		Name:          "cel.expr.conformance.proto2.Proto2ExtensionScopedMessage.nested_enum_ext",
		Tag:           "varint,1007,opt,name=nested_enum_ext,enum=cel.expr.conformance.proto2.TestAllTypes_NestedEnum",
		Filename:      "cel/expr/conformance/proto2/test_all_types_extensions.proto",
	},
	{
		ExtendedType:  (*TestAllTypes)(nil),
		ExtensionType: ([]*TestAllTypes)(nil),
		Field:         1008,
		Name:          "cel.expr.conformance.proto2.Proto2ExtensionScopedMessage.message_scoped_repeated_test_all_types",
		Tag:           "bytes,1008,rep,name=message_scoped_repeated_test_all_types",
		Filename:      "cel/expr/conformance/proto2/test_all_types_extensions.proto",
	},
}

// Extension fields to TestAllTypes.
var (
	// optional int32 int32_ext = 1000;
	E_Int32Ext = &file_cel_expr_conformance_proto2_test_all_types_extensions_proto_extTypes[0]
	// optional cel.expr.conformance.proto2.TestAllTypes nested_ext = 1001;
	E_NestedExt = &file_cel_expr_conformance_proto2_test_all_types_extensions_proto_extTypes[1]
	// optional cel.expr.conformance.proto2.TestAllTypes test_all_types_ext = 1002;
	E_TestAllTypesExt = &file_cel_expr_conformance_proto2_test_all_types_extensions_proto_extTypes[2]
	// optional cel.expr.conformance.proto2.TestAllTypes.NestedEnum nested_enum_ext = 1003;
	E_NestedEnumExt = &file_cel_expr_conformance_proto2_test_all_types_extensions_proto_extTypes[3]
	// repeated cel.expr.conformance.proto2.TestAllTypes repeated_test_all_types = 1004;
	E_RepeatedTestAllTypes = &file_cel_expr_conformance_proto2_test_all_types_extensions_proto_extTypes[4]
	// optional int64 int64_ext = 1005;
	E_Proto2ExtensionScopedMessage_Int64Ext = &file_cel_expr_conformance_proto2_test_all_types_extensions_proto_extTypes[5]
	// optional cel.expr.conformance.proto2.TestAllTypes message_scoped_nested_ext = 1006;
	E_Proto2ExtensionScopedMessage_MessageScopedNestedExt = &file_cel_expr_conformance_proto2_test_all_types_extensions_proto_extTypes[6]
	// optional cel.expr.conformance.proto2.TestAllTypes.NestedEnum nested_enum_ext = 1007;
	E_Proto2ExtensionScopedMessage_NestedEnumExt = &file_cel_expr_conformance_proto2_test_all_types_extensions_proto_extTypes[7]
	// repeated cel.expr.conformance.proto2.TestAllTypes message_scoped_repeated_test_all_types = 1008;
	E_Proto2ExtensionScopedMessage_MessageScopedRepeatedTestAllTypes = &file_cel_expr_conformance_proto2_test_all_types_extensions_proto_extTypes[8]
)

var File_cel_expr_conformance_proto2_test_all_types_extensions_proto protoreflect.FileDescriptor

const file_cel_expr_conformance_proto2_test_all_types_extensions_proto_rawDesc = "" +
	"\n" +
	";cel/expr/conformance/proto2/test_all_types_extensions.proto\x12\x1bcel.expr.conformance.proto2\x1a0cel/expr/conformance/proto2/test_all_types.proto\"\xb0\x04\n" +
	"\x1cProto2ExtensionScopedMessage2G\n" +
	"\tint64_ext\x12).cel.expr.conformance.proto2.TestAllTypes\x18\xed\a \x01(\x03R\bint64Ext2\x90\x01\n" +
	"\x19message_scoped_nested_ext\x12).cel.expr.conformance.proto2.TestAllTypes\x18\xee\a \x01(\v2).cel.expr.conformance.proto2.TestAllTypesR\x16messageScopedNestedExt2\x88\x01\n" +
	"\x0fnested_enum_ext\x12).cel.expr.conformance.proto2.TestAllTypes\x18\xef\a \x01(\x0e24.cel.expr.conformance.proto2.TestAllTypes.NestedEnumR\rnestedEnumExt2\xa8\x01\n" +
	"&message_scoped_repeated_test_all_types\x12).cel.expr.conformance.proto2.TestAllTypes\x18\xf0\a \x03(\v2).cel.expr.conformance.proto2.TestAllTypesR!messageScopedRepeatedTestAllTypes:G\n" +
	"\tint32_ext\x12).cel.expr.conformance.proto2.TestAllTypes\x18\xe8\a \x01(\x05R\bint32Ext:t\n" +
	"\n" +
	"nested_ext\x12).cel.expr.conformance.proto2.TestAllTypes\x18\xe9\a \x01(\v2).cel.expr.conformance.proto2.TestAllTypesR\tnestedExt:\x82\x01\n" +
	"\x12test_all_types_ext\x12).cel.expr.conformance.proto2.TestAllTypes\x18\xea\a \x01(\v2).cel.expr.conformance.proto2.TestAllTypesR\x0ftestAllTypesExt:\x88\x01\n" +
	"\x0fnested_enum_ext\x12).cel.expr.conformance.proto2.TestAllTypes\x18\xeb\a \x01(\x0e24.cel.expr.conformance.proto2.TestAllTypes.NestedEnumR\rnestedEnumExt:\x8c\x01\n" +
	"\x17repeated_test_all_types\x12).cel.expr.conformance.proto2.TestAllTypes\x18\xec\a \x03(\v2).cel.expr.conformance.proto2.TestAllTypesR\x14repeatedTestAllTypesB_\n" +
	"\x1fdev.cel.expr.conformance.proto2B\x16TestAllTypesExtensionsP\x01Z\x1fcel.dev/expr/conformance/proto2\xf8\x01\x01"

var (
	file_cel_expr_conformance_proto2_test_all_types_extensions_proto_rawDescOnce sync.Once
	file_cel_expr_conformance_proto2_test_all_types_extensions_proto_rawDescData []byte
)

func file_cel_expr_conformance_proto2_test_all_types_extensions_proto_rawDescGZIP() []byte {
	file_cel_expr_conformance_proto2_test_all_types_extensions_proto_rawDescOnce.Do(func() {
		file_cel_expr_conformance_proto2_test_all_types_extensions_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cel_expr_conformance_proto2_test_all_types_extensions_proto_rawDesc), len(file_cel_expr_conformance_proto2_test_all_types_extensions_proto_rawDesc)))
	})
	return file_cel_expr_conformance_proto2_test_all_types_extensions_proto_rawDescData
}

var file_cel_expr_conformance_proto2_test_all_types_extensions_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_cel_expr_conformance_proto2_test_all_types_extensions_proto_goTypes = []any{
	(*Proto2ExtensionScopedMessage)(nil), // 0: cel.expr.conformance.proto2.Proto2ExtensionScopedMessage
	(*TestAllTypes)(nil),                 // 1: cel.expr.conformance.proto2.TestAllTypes
	(TestAllTypes_NestedEnum)(0),         // 2: cel.expr.conformance.proto2.TestAllTypes.NestedEnum
}
var file_cel_expr_conformance_proto2_test_all_types_extensions_proto_depIdxs = []int32{
	1,  // 0: cel.expr.conformance.proto2.int32_ext:extendee -> cel.expr.conformance.proto2.TestAllTypes
	1,  // 1: cel.expr.conformance.proto2.nested_ext:extendee -> cel.expr.conformance.proto2.TestAllTypes
	1,  // 2: cel.expr.conformance.proto2.test_all_types_ext:extendee -> cel.expr.conformance.proto2.TestAllTypes
	1,  // 3: cel.expr.conformance.proto2.nested_enum_ext:extendee -> cel.expr.conformance.proto2.TestAllTypes
	1,  // 4: cel.expr.conformance.proto2.repeated_test_all_types:extendee -> cel.expr.conformance.proto2.TestAllTypes
	1,  // 5: cel.expr.conformance.proto2.Proto2ExtensionScopedMessage.int64_ext:extendee -> cel.expr.conformance.proto2.TestAllTypes
	1,  // 6: cel.expr.conformance.proto2.Proto2ExtensionScopedMessage.message_scoped_nested_ext:extendee -> cel.expr.conformance.proto2.TestAllTypes
	1,  // 7: cel.expr.conformance.proto2.Proto2ExtensionScopedMessage.nested_enum_ext:extendee -> cel.expr.conformance.proto2.TestAllTypes
	1,  // 8: cel.expr.conformance.proto2.Proto2ExtensionScopedMessage.message_scoped_repeated_test_all_types:extendee -> cel.expr.conformance.proto2.TestAllTypes
	1,  // 9: cel.expr.conformance.proto2.nested_ext:type_name -> cel.expr.conformance.proto2.TestAllTypes
	1,  // 10: cel.expr.conformance.proto2.test_all_types_ext:type_name -> cel.expr.conformance.proto2.TestAllTypes
	2,  // 11: cel.expr.conformance.proto2.nested_enum_ext:type_name -> cel.expr.conformance.proto2.TestAllTypes.NestedEnum
	1,  // 12: cel.expr.conformance.proto2.repeated_test_all_types:type_name -> cel.expr.conformance.proto2.TestAllTypes
	1,  // 13: cel.expr.conformance.proto2.Proto2ExtensionScopedMessage.message_scoped_nested_ext:type_name -> cel.expr.conformance.proto2.TestAllTypes
	2,  // 14: cel.expr.conformance.proto2.Proto2ExtensionScopedMessage.nested_enum_ext:type_name -> cel.expr.conformance.proto2.TestAllTypes.NestedEnum
	1,  // 15: cel.expr.conformance.proto2.Proto2ExtensionScopedMessage.message_scoped_repeated_test_all_types:type_name -> cel.expr.conformance.proto2.TestAllTypes
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	9,  // [9:16] is the sub-list for extension type_name
	0,  // [0:9] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_cel_expr_conformance_proto2_test_all_types_extensions_proto_init() }
func file_cel_expr_conformance_proto2_test_all_types_extensions_proto_init() {
	if File_cel_expr_conformance_proto2_test_all_types_extensions_proto != nil {
		return
	}
	file_cel_expr_conformance_proto2_test_all_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cel_expr_conformance_proto2_test_all_types_extensions_proto_rawDesc), len(file_cel_expr_conformance_proto2_test_all_types_extensions_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 9,
			NumServices:   0,
		},
		GoTypes:           file_cel_expr_conformance_proto2_test_all_types_extensions_proto_goTypes,
		DependencyIndexes: file_cel_expr_conformance_proto2_test_all_types_extensions_proto_depIdxs,
		MessageInfos:      file_cel_expr_conformance_proto2_test_all_types_extensions_proto_msgTypes,
		ExtensionInfos:    file_cel_expr_conformance_proto2_test_all_types_extensions_proto_extTypes,
	}.Build()
	File_cel_expr_conformance_proto2_test_all_types_extensions_proto = out.File
	file_cel_expr_conformance_proto2_test_all_types_extensions_proto_goTypes = nil
	file_cel_expr_conformance_proto2_test_all_types_extensions_proto_depIdxs = nil
}
