// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/v1/value.proto

/*
Package v1 is a generated protocol buffer package.

It is generated from these files:
	proto/v1/value.proto

It has these top-level messages:
	Value
	ListValue
	MapValue
*/
package value

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/any"
import google_protobuf1 "github.com/golang/protobuf/ptypes/duration"
import google_protobuf2 "github.com/golang/protobuf/ptypes/struct"
import google_protobuf3 "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Value struct {
	// Types that are valid to be assigned to Kind:
	//	*Value_NullValue
	//	*Value_BoolValue
	//	*Value_Int64Value
	//	*Value_Uint64Value
	//	*Value_DoubleValue
	//	*Value_StringValue
	//	*Value_BytesValue
	//	*Value_DurationValue
	//	*Value_TimestampValue
	//	*Value_MessageValue
	//	*Value_MapValue
	//	*Value_ListValue
	Kind isValue_Kind `protobuf_oneof:"kind"`
}

func (m *Value) Reset()                    { *m = Value{} }
func (m *Value) String() string            { return proto.CompactTextString(m) }
func (*Value) ProtoMessage()               {}
func (*Value) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type isValue_Kind interface{ isValue_Kind() }

type Value_NullValue struct {
	NullValue google_protobuf2.NullValue `protobuf:"varint,1,opt,name=null_value,json=nullValue,enum=google.protobuf.NullValue,oneof"`
}
type Value_BoolValue struct {
	BoolValue bool `protobuf:"varint,2,opt,name=bool_value,json=boolValue,oneof"`
}
type Value_Int64Value struct {
	Int64Value int64 `protobuf:"varint,3,opt,name=int64_value,json=int64Value,oneof"`
}
type Value_Uint64Value struct {
	Uint64Value uint64 `protobuf:"varint,4,opt,name=uint64_value,json=uint64Value,oneof"`
}
type Value_DoubleValue struct {
	DoubleValue float64 `protobuf:"fixed64,5,opt,name=double_value,json=doubleValue,oneof"`
}
type Value_StringValue struct {
	StringValue string `protobuf:"bytes,6,opt,name=string_value,json=stringValue,oneof"`
}
type Value_BytesValue struct {
	BytesValue []byte `protobuf:"bytes,7,opt,name=bytes_value,json=bytesValue,proto3,oneof"`
}
type Value_DurationValue struct {
	DurationValue *google_protobuf1.Duration `protobuf:"bytes,8,opt,name=duration_value,json=durationValue,oneof"`
}
type Value_TimestampValue struct {
	TimestampValue *google_protobuf3.Timestamp `protobuf:"bytes,9,opt,name=timestamp_value,json=timestampValue,oneof"`
}
type Value_MessageValue struct {
	MessageValue *google_protobuf.Any `protobuf:"bytes,10,opt,name=message_value,json=messageValue,oneof"`
}
type Value_MapValue struct {
	MapValue *MapValue `protobuf:"bytes,11,opt,name=map_value,json=mapValue,oneof"`
}
type Value_ListValue struct {
	ListValue *ListValue `protobuf:"bytes,12,opt,name=list_value,json=listValue,oneof"`
}

func (*Value_NullValue) isValue_Kind()      {}
func (*Value_BoolValue) isValue_Kind()      {}
func (*Value_Int64Value) isValue_Kind()     {}
func (*Value_Uint64Value) isValue_Kind()    {}
func (*Value_DoubleValue) isValue_Kind()    {}
func (*Value_StringValue) isValue_Kind()    {}
func (*Value_BytesValue) isValue_Kind()     {}
func (*Value_DurationValue) isValue_Kind()  {}
func (*Value_TimestampValue) isValue_Kind() {}
func (*Value_MessageValue) isValue_Kind()   {}
func (*Value_MapValue) isValue_Kind()       {}
func (*Value_ListValue) isValue_Kind()      {}

func (m *Value) GetKind() isValue_Kind {
	if m != nil {
		return m.Kind
	}
	return nil
}

func (m *Value) GetNullValue() google_protobuf2.NullValue {
	if x, ok := m.GetKind().(*Value_NullValue); ok {
		return x.NullValue
	}
	return google_protobuf2.NullValue_NULL_VALUE
}

func (m *Value) GetBoolValue() bool {
	if x, ok := m.GetKind().(*Value_BoolValue); ok {
		return x.BoolValue
	}
	return false
}

func (m *Value) GetInt64Value() int64 {
	if x, ok := m.GetKind().(*Value_Int64Value); ok {
		return x.Int64Value
	}
	return 0
}

func (m *Value) GetUint64Value() uint64 {
	if x, ok := m.GetKind().(*Value_Uint64Value); ok {
		return x.Uint64Value
	}
	return 0
}

func (m *Value) GetDoubleValue() float64 {
	if x, ok := m.GetKind().(*Value_DoubleValue); ok {
		return x.DoubleValue
	}
	return 0
}

func (m *Value) GetStringValue() string {
	if x, ok := m.GetKind().(*Value_StringValue); ok {
		return x.StringValue
	}
	return ""
}

func (m *Value) GetBytesValue() []byte {
	if x, ok := m.GetKind().(*Value_BytesValue); ok {
		return x.BytesValue
	}
	return nil
}

func (m *Value) GetDurationValue() *google_protobuf1.Duration {
	if x, ok := m.GetKind().(*Value_DurationValue); ok {
		return x.DurationValue
	}
	return nil
}

func (m *Value) GetTimestampValue() *google_protobuf3.Timestamp {
	if x, ok := m.GetKind().(*Value_TimestampValue); ok {
		return x.TimestampValue
	}
	return nil
}

func (m *Value) GetMessageValue() *google_protobuf.Any {
	if x, ok := m.GetKind().(*Value_MessageValue); ok {
		return x.MessageValue
	}
	return nil
}

func (m *Value) GetMapValue() *MapValue {
	if x, ok := m.GetKind().(*Value_MapValue); ok {
		return x.MapValue
	}
	return nil
}

func (m *Value) GetListValue() *ListValue {
	if x, ok := m.GetKind().(*Value_ListValue); ok {
		return x.ListValue
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Value) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Value_OneofMarshaler, _Value_OneofUnmarshaler, _Value_OneofSizer, []interface{}{
		(*Value_NullValue)(nil),
		(*Value_BoolValue)(nil),
		(*Value_Int64Value)(nil),
		(*Value_Uint64Value)(nil),
		(*Value_DoubleValue)(nil),
		(*Value_StringValue)(nil),
		(*Value_BytesValue)(nil),
		(*Value_DurationValue)(nil),
		(*Value_TimestampValue)(nil),
		(*Value_MessageValue)(nil),
		(*Value_MapValue)(nil),
		(*Value_ListValue)(nil),
	}
}

func _Value_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Value)
	// kind
	switch x := m.Kind.(type) {
	case *Value_NullValue:
		b.EncodeVarint(1<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.NullValue))
	case *Value_BoolValue:
		t := uint64(0)
		if x.BoolValue {
			t = 1
		}
		b.EncodeVarint(2<<3 | proto.WireVarint)
		b.EncodeVarint(t)
	case *Value_Int64Value:
		b.EncodeVarint(3<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.Int64Value))
	case *Value_Uint64Value:
		b.EncodeVarint(4<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.Uint64Value))
	case *Value_DoubleValue:
		b.EncodeVarint(5<<3 | proto.WireFixed64)
		b.EncodeFixed64(math.Float64bits(x.DoubleValue))
	case *Value_StringValue:
		b.EncodeVarint(6<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.StringValue)
	case *Value_BytesValue:
		b.EncodeVarint(7<<3 | proto.WireBytes)
		b.EncodeRawBytes(x.BytesValue)
	case *Value_DurationValue:
		b.EncodeVarint(8<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.DurationValue); err != nil {
			return err
		}
	case *Value_TimestampValue:
		b.EncodeVarint(9<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.TimestampValue); err != nil {
			return err
		}
	case *Value_MessageValue:
		b.EncodeVarint(10<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.MessageValue); err != nil {
			return err
		}
	case *Value_MapValue:
		b.EncodeVarint(11<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.MapValue); err != nil {
			return err
		}
	case *Value_ListValue:
		b.EncodeVarint(12<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ListValue); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Value.Kind has unexpected type %T", x)
	}
	return nil
}

func _Value_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Value)
	switch tag {
	case 1: // kind.null_value
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Kind = &Value_NullValue{google_protobuf2.NullValue(x)}
		return true, err
	case 2: // kind.bool_value
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Kind = &Value_BoolValue{x != 0}
		return true, err
	case 3: // kind.int64_value
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Kind = &Value_Int64Value{int64(x)}
		return true, err
	case 4: // kind.uint64_value
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Kind = &Value_Uint64Value{x}
		return true, err
	case 5: // kind.double_value
		if wire != proto.WireFixed64 {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeFixed64()
		m.Kind = &Value_DoubleValue{math.Float64frombits(x)}
		return true, err
	case 6: // kind.string_value
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Kind = &Value_StringValue{x}
		return true, err
	case 7: // kind.bytes_value
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeRawBytes(true)
		m.Kind = &Value_BytesValue{x}
		return true, err
	case 8: // kind.duration_value
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(google_protobuf1.Duration)
		err := b.DecodeMessage(msg)
		m.Kind = &Value_DurationValue{msg}
		return true, err
	case 9: // kind.timestamp_value
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(google_protobuf3.Timestamp)
		err := b.DecodeMessage(msg)
		m.Kind = &Value_TimestampValue{msg}
		return true, err
	case 10: // kind.message_value
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(google_protobuf.Any)
		err := b.DecodeMessage(msg)
		m.Kind = &Value_MessageValue{msg}
		return true, err
	case 11: // kind.map_value
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(MapValue)
		err := b.DecodeMessage(msg)
		m.Kind = &Value_MapValue{msg}
		return true, err
	case 12: // kind.list_value
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ListValue)
		err := b.DecodeMessage(msg)
		m.Kind = &Value_ListValue{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Value_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Value)
	// kind
	switch x := m.Kind.(type) {
	case *Value_NullValue:
		n += proto.SizeVarint(1<<3 | proto.WireVarint)
		n += proto.SizeVarint(uint64(x.NullValue))
	case *Value_BoolValue:
		n += proto.SizeVarint(2<<3 | proto.WireVarint)
		n += 1
	case *Value_Int64Value:
		n += proto.SizeVarint(3<<3 | proto.WireVarint)
		n += proto.SizeVarint(uint64(x.Int64Value))
	case *Value_Uint64Value:
		n += proto.SizeVarint(4<<3 | proto.WireVarint)
		n += proto.SizeVarint(uint64(x.Uint64Value))
	case *Value_DoubleValue:
		n += proto.SizeVarint(5<<3 | proto.WireFixed64)
		n += 8
	case *Value_StringValue:
		n += proto.SizeVarint(6<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.StringValue)))
		n += len(x.StringValue)
	case *Value_BytesValue:
		n += proto.SizeVarint(7<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.BytesValue)))
		n += len(x.BytesValue)
	case *Value_DurationValue:
		s := proto.Size(x.DurationValue)
		n += proto.SizeVarint(8<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Value_TimestampValue:
		s := proto.Size(x.TimestampValue)
		n += proto.SizeVarint(9<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Value_MessageValue:
		s := proto.Size(x.MessageValue)
		n += proto.SizeVarint(10<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Value_MapValue:
		s := proto.Size(x.MapValue)
		n += proto.SizeVarint(11<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Value_ListValue:
		s := proto.Size(x.ListValue)
		n += proto.SizeVarint(12<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type ListValue struct {
	Values []*Value `protobuf:"bytes,1,rep,name=values" json:"values,omitempty"`
}

func (m *ListValue) Reset()                    { *m = ListValue{} }
func (m *ListValue) String() string            { return proto.CompactTextString(m) }
func (*ListValue) ProtoMessage()               {}
func (*ListValue) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ListValue) GetValues() []*Value {
	if m != nil {
		return m.Values
	}
	return nil
}

type MapValue struct {
	Entries []*MapValue_Entry `protobuf:"bytes,1,rep,name=entries" json:"entries,omitempty"`
}

func (m *MapValue) Reset()                    { *m = MapValue{} }
func (m *MapValue) String() string            { return proto.CompactTextString(m) }
func (*MapValue) ProtoMessage()               {}
func (*MapValue) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *MapValue) GetEntries() []*MapValue_Entry {
	if m != nil {
		return m.Entries
	}
	return nil
}

type MapValue_Entry struct {
	Key   *Value `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value *Value `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
}

func (m *MapValue_Entry) Reset()                    { *m = MapValue_Entry{} }
func (m *MapValue_Entry) String() string            { return proto.CompactTextString(m) }
func (*MapValue_Entry) ProtoMessage()               {}
func (*MapValue_Entry) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 0} }

func (m *MapValue_Entry) GetKey() *Value {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *MapValue_Entry) GetValue() *Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func init() {
	proto.RegisterType((*Value)(nil), "google.api.expr.v1.Value")
	proto.RegisterType((*ListValue)(nil), "google.api.expr.v1.ListValue")
	proto.RegisterType((*MapValue)(nil), "google.api.expr.v1.MapValue")
	proto.RegisterType((*MapValue_Entry)(nil), "google.api.expr.v1.MapValue.Entry")
}

func init() { proto.RegisterFile("proto/v1/value.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 490 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0xdf, 0x8a, 0xd3, 0x40,
	0x14, 0xc6, 0x33, 0xf6, 0xcf, 0x36, 0xa7, 0xdd, 0x0a, 0x61, 0x91, 0xdd, 0xb2, 0xba, 0xb1, 0xde,
	0x44, 0x84, 0x84, 0xae, 0xe2, 0x8d, 0xb2, 0x60, 0x71, 0x21, 0x17, 0x2a, 0x4b, 0x10, 0x6f, 0x25,
	0xd9, 0x8e, 0x65, 0xd8, 0xc9, 0x4c, 0xc8, 0xcc, 0x14, 0xf3, 0x54, 0x3e, 0x96, 0xaf, 0xe0, 0xa5,
	0x64, 0xfe, 0xc4, 0xda, 0x96, 0xde, 0x75, 0xce, 0xf9, 0x7d, 0x5f, 0xbf, 0x9c, 0x73, 0xe0, 0xac,
	0xaa, 0xb9, 0xe4, 0xc9, 0x66, 0x91, 0x6c, 0x72, 0xaa, 0x70, 0xac, 0x9f, 0x41, 0xb0, 0xe6, 0x7c,
	0x4d, 0x71, 0x9c, 0x57, 0x24, 0xc6, 0x3f, 0xab, 0x3a, 0xde, 0x2c, 0x66, 0x17, 0xa6, 0x96, 0x68,
	0xa2, 0x50, 0x3f, 0x92, 0x9c, 0x35, 0x06, 0x9f, 0x3d, 0xdb, 0x6d, 0xad, 0x54, 0x9d, 0x4b, 0xc2,
	0x99, 0xed, 0x5f, 0xee, 0xf6, 0x85, 0xac, 0xd5, 0xbd, 0xb4, 0xdd, 0xab, 0xdd, 0xae, 0x24, 0x25,
	0x16, 0x32, 0x2f, 0x2b, 0x03, 0xcc, 0x7f, 0xf7, 0x61, 0xf0, 0xad, 0x4d, 0x17, 0xbc, 0x03, 0x60,
	0x8a, 0xd2, 0xef, 0x3a, 0xeb, 0x39, 0x0a, 0x51, 0x34, 0xbd, 0x9e, 0xc5, 0x36, 0xac, 0xd3, 0xc7,
	0x5f, 0x14, 0xa5, 0x9a, 0x4f, 0xbd, 0xcc, 0x67, 0xee, 0x11, 0x5c, 0x01, 0x14, 0x9c, 0x3b, 0xf1,
	0xa3, 0x10, 0x45, 0xa3, 0x16, 0x68, 0x6b, 0x06, 0x78, 0x0e, 0x63, 0xc2, 0xe4, 0xdb, 0x37, 0x96,
	0xe8, 0x85, 0x28, 0xea, 0xa5, 0x5e, 0x06, 0xba, 0x68, 0x90, 0x17, 0x30, 0x51, 0xdb, 0x4c, 0x3f,
	0x44, 0x51, 0x3f, 0xf5, 0xb2, 0xb1, 0xfa, 0x1f, 0x5a, 0x71, 0x55, 0x50, 0x6c, 0xa1, 0x41, 0x88,
	0x22, 0xd4, 0x42, 0xa6, 0xda, 0x41, 0x42, 0xd6, 0x84, 0xad, 0x2d, 0x34, 0x0c, 0x51, 0xe4, 0xb7,
	0x90, 0xa9, 0x76, 0x89, 0x8a, 0x46, 0x62, 0x61, 0x99, 0x93, 0x10, 0x45, 0x93, 0x36, 0x91, 0x2e,
	0x1a, 0x64, 0x09, 0x53, 0x37, 0x6d, 0x4b, 0x8d, 0x42, 0x14, 0x8d, 0xaf, 0x2f, 0xf6, 0xc6, 0xf2,
	0xd1, 0x62, 0xa9, 0x97, 0x9d, 0x3a, 0x89, 0xf1, 0xb8, 0x85, 0xc7, 0xdd, 0xcc, 0xad, 0x89, 0xaf,
	0x4d, 0xf6, 0x67, 0xfb, 0xd5, 0x71, 0xa9, 0x97, 0x4d, 0x3b, 0x91, 0xdb, 0xce, 0x69, 0x89, 0x85,
	0xc8, 0xd7, 0xee, 0xc3, 0x41, 0x9b, 0x9c, 0xed, 0x99, 0x7c, 0x60, 0x4d, 0xea, 0x65, 0x13, 0x0b,
	0x3b, 0xb1, 0x5f, 0xe6, 0xee, 0xdf, 0xc7, 0x5a, 0x78, 0x19, 0xef, 0x9f, 0x61, 0xfc, 0x39, 0xaf,
	0xdc, 0x6e, 0x47, 0xa5, 0xfd, 0x1d, 0xdc, 0x00, 0x50, 0x22, 0xa4, 0x55, 0x4f, 0xb4, 0xfa, 0xe9,
	0x21, 0xf5, 0x27, 0x22, 0x64, 0x77, 0x1a, 0xd4, 0x3d, 0x96, 0x43, 0xe8, 0x3f, 0x10, 0xb6, 0x9a,
	0xdf, 0x80, 0xdf, 0x11, 0xc1, 0x02, 0x86, 0xda, 0x4f, 0x9c, 0xa3, 0xb0, 0xb7, 0x3d, 0xd1, 0x6d,
	0x43, 0x8d, 0x66, 0x16, 0x9c, 0xff, 0x42, 0x30, 0x72, 0x01, 0x83, 0xf7, 0x70, 0x82, 0x99, 0xac,
	0x49, 0x67, 0x30, 0x3f, 0xf6, 0x3d, 0xf1, 0x2d, 0x93, 0x75, 0x93, 0x39, 0xc9, 0x0c, 0xc3, 0x40,
	0x57, 0x82, 0x57, 0xd0, 0x7b, 0xc0, 0x8d, 0x3e, 0xf6, 0xa3, 0x19, 0x5a, 0x2a, 0x48, 0x60, 0xf0,
	0xef, 0xbc, 0x8f, 0xe2, 0x86, 0x5b, 0xbe, 0x84, 0x27, 0xf7, 0xbc, 0x3c, 0x80, 0x2d, 0x41, 0x73,
	0x77, 0xed, 0xce, 0xee, 0xd0, 0x1f, 0x84, 0x8a, 0xa1, 0xde, 0xdf, 0xeb, 0xbf, 0x01, 0x00, 0x00,
	0xff, 0xff, 0x56, 0xbf, 0xec, 0xca, 0x33, 0x04, 0x00, 0x00,
}
