// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.27.1
// source: cel/expr/conformance/conformance_service.proto

package conformance

import (
	expr "cel.dev/expr"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IssueDetails_Severity int32

const (
	IssueDetails_SEVERITY_UNSPECIFIED IssueDetails_Severity = 0
	IssueDetails_DEPRECATION          IssueDetails_Severity = 1
	IssueDetails_WARNING              IssueDetails_Severity = 2
	IssueDetails_ERROR                IssueDetails_Severity = 3
)

// Enum value maps for IssueDetails_Severity.
var (
	IssueDetails_Severity_name = map[int32]string{
		0: "SEVERITY_UNSPECIFIED",
		1: "DEPRECATION",
		2: "WARNING",
		3: "ERROR",
	}
	IssueDetails_Severity_value = map[string]int32{
		"SEVERITY_UNSPECIFIED": 0,
		"DEPRECATION":          1,
		"WARNING":              2,
		"ERROR":                3,
	}
)

func (x IssueDetails_Severity) Enum() *IssueDetails_Severity {
	p := new(IssueDetails_Severity)
	*p = x
	return p
}

func (x IssueDetails_Severity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IssueDetails_Severity) Descriptor() protoreflect.EnumDescriptor {
	return file_cel_expr_conformance_conformance_service_proto_enumTypes[0].Descriptor()
}

func (IssueDetails_Severity) Type() protoreflect.EnumType {
	return &file_cel_expr_conformance_conformance_service_proto_enumTypes[0]
}

func (x IssueDetails_Severity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IssueDetails_Severity.Descriptor instead.
func (IssueDetails_Severity) EnumDescriptor() ([]byte, []int) {
	return file_cel_expr_conformance_conformance_service_proto_rawDescGZIP(), []int{7, 0}
}

type ParseRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CelSource      string                 `protobuf:"bytes,1,opt,name=cel_source,json=celSource,proto3" json:"cel_source,omitempty"`
	SyntaxVersion  string                 `protobuf:"bytes,2,opt,name=syntax_version,json=syntaxVersion,proto3" json:"syntax_version,omitempty"`
	SourceLocation string                 `protobuf:"bytes,3,opt,name=source_location,json=sourceLocation,proto3" json:"source_location,omitempty"`
	DisableMacros  bool                   `protobuf:"varint,4,opt,name=disable_macros,json=disableMacros,proto3" json:"disable_macros,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ParseRequest) Reset() {
	*x = ParseRequest{}
	mi := &file_cel_expr_conformance_conformance_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseRequest) ProtoMessage() {}

func (x *ParseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cel_expr_conformance_conformance_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseRequest.ProtoReflect.Descriptor instead.
func (*ParseRequest) Descriptor() ([]byte, []int) {
	return file_cel_expr_conformance_conformance_service_proto_rawDescGZIP(), []int{0}
}

func (x *ParseRequest) GetCelSource() string {
	if x != nil {
		return x.CelSource
	}
	return ""
}

func (x *ParseRequest) GetSyntaxVersion() string {
	if x != nil {
		return x.SyntaxVersion
	}
	return ""
}

func (x *ParseRequest) GetSourceLocation() string {
	if x != nil {
		return x.SourceLocation
	}
	return ""
}

func (x *ParseRequest) GetDisableMacros() bool {
	if x != nil {
		return x.DisableMacros
	}
	return false
}

type ParseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParsedExpr    *expr.ParsedExpr       `protobuf:"bytes,1,opt,name=parsed_expr,json=parsedExpr,proto3" json:"parsed_expr,omitempty"`
	Issues        *expr.ErrorSet         `protobuf:"bytes,2,opt,name=issues,proto3" json:"issues,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseResponse) Reset() {
	*x = ParseResponse{}
	mi := &file_cel_expr_conformance_conformance_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseResponse) ProtoMessage() {}

func (x *ParseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cel_expr_conformance_conformance_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseResponse.ProtoReflect.Descriptor instead.
func (*ParseResponse) Descriptor() ([]byte, []int) {
	return file_cel_expr_conformance_conformance_service_proto_rawDescGZIP(), []int{1}
}

func (x *ParseResponse) GetParsedExpr() *expr.ParsedExpr {
	if x != nil {
		return x.ParsedExpr
	}
	return nil
}

func (x *ParseResponse) GetIssues() *expr.ErrorSet {
	if x != nil {
		return x.Issues
	}
	return nil
}

type CheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParsedExpr    *expr.ParsedExpr       `protobuf:"bytes,1,opt,name=parsed_expr,json=parsedExpr,proto3" json:"parsed_expr,omitempty"`
	TypeEnv       []*expr.Decl           `protobuf:"bytes,2,rep,name=type_env,json=typeEnv,proto3" json:"type_env,omitempty"`
	Container     string                 `protobuf:"bytes,3,opt,name=container,proto3" json:"container,omitempty"`
	NoStdEnv      bool                   `protobuf:"varint,4,opt,name=no_std_env,json=noStdEnv,proto3" json:"no_std_env,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckRequest) Reset() {
	*x = CheckRequest{}
	mi := &file_cel_expr_conformance_conformance_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRequest) ProtoMessage() {}

func (x *CheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cel_expr_conformance_conformance_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRequest.ProtoReflect.Descriptor instead.
func (*CheckRequest) Descriptor() ([]byte, []int) {
	return file_cel_expr_conformance_conformance_service_proto_rawDescGZIP(), []int{2}
}

func (x *CheckRequest) GetParsedExpr() *expr.ParsedExpr {
	if x != nil {
		return x.ParsedExpr
	}
	return nil
}

func (x *CheckRequest) GetTypeEnv() []*expr.Decl {
	if x != nil {
		return x.TypeEnv
	}
	return nil
}

func (x *CheckRequest) GetContainer() string {
	if x != nil {
		return x.Container
	}
	return ""
}

func (x *CheckRequest) GetNoStdEnv() bool {
	if x != nil {
		return x.NoStdEnv
	}
	return false
}

type CheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CheckedExpr   *expr.CheckedExpr      `protobuf:"bytes,1,opt,name=checked_expr,json=checkedExpr,proto3" json:"checked_expr,omitempty"`
	Issues        *expr.ErrorSet         `protobuf:"bytes,2,opt,name=issues,proto3" json:"issues,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckResponse) Reset() {
	*x = CheckResponse{}
	mi := &file_cel_expr_conformance_conformance_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckResponse) ProtoMessage() {}

func (x *CheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cel_expr_conformance_conformance_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckResponse.ProtoReflect.Descriptor instead.
func (*CheckResponse) Descriptor() ([]byte, []int) {
	return file_cel_expr_conformance_conformance_service_proto_rawDescGZIP(), []int{3}
}

func (x *CheckResponse) GetCheckedExpr() *expr.CheckedExpr {
	if x != nil {
		return x.CheckedExpr
	}
	return nil
}

func (x *CheckResponse) GetIssues() *expr.ErrorSet {
	if x != nil {
		return x.Issues
	}
	return nil
}

type EvalRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to ExprKind:
	//
	//	*EvalRequest_ParsedExpr
	//	*EvalRequest_CheckedExpr
	ExprKind      isEvalRequest_ExprKind     `protobuf_oneof:"expr_kind"`
	Bindings      map[string]*expr.ExprValue `protobuf:"bytes,3,rep,name=bindings,proto3" json:"bindings,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Container     string                     `protobuf:"bytes,4,opt,name=container,proto3" json:"container,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvalRequest) Reset() {
	*x = EvalRequest{}
	mi := &file_cel_expr_conformance_conformance_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvalRequest) ProtoMessage() {}

func (x *EvalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cel_expr_conformance_conformance_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvalRequest.ProtoReflect.Descriptor instead.
func (*EvalRequest) Descriptor() ([]byte, []int) {
	return file_cel_expr_conformance_conformance_service_proto_rawDescGZIP(), []int{4}
}

func (x *EvalRequest) GetExprKind() isEvalRequest_ExprKind {
	if x != nil {
		return x.ExprKind
	}
	return nil
}

func (x *EvalRequest) GetParsedExpr() *expr.ParsedExpr {
	if x != nil {
		if x, ok := x.ExprKind.(*EvalRequest_ParsedExpr); ok {
			return x.ParsedExpr
		}
	}
	return nil
}

func (x *EvalRequest) GetCheckedExpr() *expr.CheckedExpr {
	if x != nil {
		if x, ok := x.ExprKind.(*EvalRequest_CheckedExpr); ok {
			return x.CheckedExpr
		}
	}
	return nil
}

func (x *EvalRequest) GetBindings() map[string]*expr.ExprValue {
	if x != nil {
		return x.Bindings
	}
	return nil
}

func (x *EvalRequest) GetContainer() string {
	if x != nil {
		return x.Container
	}
	return ""
}

type isEvalRequest_ExprKind interface {
	isEvalRequest_ExprKind()
}

type EvalRequest_ParsedExpr struct {
	ParsedExpr *expr.ParsedExpr `protobuf:"bytes,1,opt,name=parsed_expr,json=parsedExpr,proto3,oneof"`
}

type EvalRequest_CheckedExpr struct {
	CheckedExpr *expr.CheckedExpr `protobuf:"bytes,2,opt,name=checked_expr,json=checkedExpr,proto3,oneof"`
}

func (*EvalRequest_ParsedExpr) isEvalRequest_ExprKind() {}

func (*EvalRequest_CheckedExpr) isEvalRequest_ExprKind() {}

type EvalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *expr.ExprValue        `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Issues        *expr.ErrorSet         `protobuf:"bytes,2,opt,name=issues,proto3" json:"issues,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvalResponse) Reset() {
	*x = EvalResponse{}
	mi := &file_cel_expr_conformance_conformance_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvalResponse) ProtoMessage() {}

func (x *EvalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cel_expr_conformance_conformance_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvalResponse.ProtoReflect.Descriptor instead.
func (*EvalResponse) Descriptor() ([]byte, []int) {
	return file_cel_expr_conformance_conformance_service_proto_rawDescGZIP(), []int{5}
}

func (x *EvalResponse) GetResult() *expr.ExprValue {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *EvalResponse) GetIssues() *expr.ErrorSet {
	if x != nil {
		return x.Issues
	}
	return nil
}

type SourcePosition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Location      string                 `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Line          int32                  `protobuf:"varint,3,opt,name=line,proto3" json:"line,omitempty"`
	Column        int32                  `protobuf:"varint,4,opt,name=column,proto3" json:"column,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SourcePosition) Reset() {
	*x = SourcePosition{}
	mi := &file_cel_expr_conformance_conformance_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourcePosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourcePosition) ProtoMessage() {}

func (x *SourcePosition) ProtoReflect() protoreflect.Message {
	mi := &file_cel_expr_conformance_conformance_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourcePosition.ProtoReflect.Descriptor instead.
func (*SourcePosition) Descriptor() ([]byte, []int) {
	return file_cel_expr_conformance_conformance_service_proto_rawDescGZIP(), []int{6}
}

func (x *SourcePosition) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *SourcePosition) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *SourcePosition) GetLine() int32 {
	if x != nil {
		return x.Line
	}
	return 0
}

func (x *SourcePosition) GetColumn() int32 {
	if x != nil {
		return x.Column
	}
	return 0
}

type IssueDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Severity      IssueDetails_Severity  `protobuf:"varint,1,opt,name=severity,proto3,enum=cel.expr.conformance.IssueDetails_Severity" json:"severity,omitempty"`
	Position      *SourcePosition        `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"`
	Id            int64                  `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueDetails) Reset() {
	*x = IssueDetails{}
	mi := &file_cel_expr_conformance_conformance_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueDetails) ProtoMessage() {}

func (x *IssueDetails) ProtoReflect() protoreflect.Message {
	mi := &file_cel_expr_conformance_conformance_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueDetails.ProtoReflect.Descriptor instead.
func (*IssueDetails) Descriptor() ([]byte, []int) {
	return file_cel_expr_conformance_conformance_service_proto_rawDescGZIP(), []int{7}
}

func (x *IssueDetails) GetSeverity() IssueDetails_Severity {
	if x != nil {
		return x.Severity
	}
	return IssueDetails_SEVERITY_UNSPECIFIED
}

func (x *IssueDetails) GetPosition() *SourcePosition {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *IssueDetails) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_cel_expr_conformance_conformance_service_proto protoreflect.FileDescriptor

const file_cel_expr_conformance_conformance_service_proto_rawDesc = "" +
	"\n" +
	".cel/expr/conformance/conformance_service.proto\x12\x14cel.expr.conformance\x1a\x16cel/expr/checked.proto\x1a\x13cel/expr/eval.proto\x1a\x15cel/expr/syntax.proto\"\xa4\x01\n" +
	"\fParseRequest\x12\x1d\n" +
	"\n" +
	"cel_source\x18\x01 \x01(\tR\tcelSource\x12%\n" +
	"\x0esyntax_version\x18\x02 \x01(\tR\rsyntaxVersion\x12'\n" +
	"\x0fsource_location\x18\x03 \x01(\tR\x0esourceLocation\x12%\n" +
	"\x0edisable_macros\x18\x04 \x01(\bR\rdisableMacros\"r\n" +
	"\rParseResponse\x125\n" +
	"\vparsed_expr\x18\x01 \x01(\v2\x14.cel.expr.ParsedExprR\n" +
	"parsedExpr\x12*\n" +
	"\x06issues\x18\x02 \x01(\v2\x12.cel.expr.ErrorSetR\x06issues\"\xac\x01\n" +
	"\fCheckRequest\x125\n" +
	"\vparsed_expr\x18\x01 \x01(\v2\x14.cel.expr.ParsedExprR\n" +
	"parsedExpr\x12)\n" +
	"\btype_env\x18\x02 \x03(\v2\x0e.cel.expr.DeclR\atypeEnv\x12\x1c\n" +
	"\tcontainer\x18\x03 \x01(\tR\tcontainer\x12\x1c\n" +
	"\n" +
	"no_std_env\x18\x04 \x01(\bR\bnoStdEnv\"u\n" +
	"\rCheckResponse\x128\n" +
	"\fchecked_expr\x18\x01 \x01(\v2\x15.cel.expr.CheckedExprR\vcheckedExpr\x12*\n" +
	"\x06issues\x18\x02 \x01(\v2\x12.cel.expr.ErrorSetR\x06issues\"\xcc\x02\n" +
	"\vEvalRequest\x127\n" +
	"\vparsed_expr\x18\x01 \x01(\v2\x14.cel.expr.ParsedExprH\x00R\n" +
	"parsedExpr\x12:\n" +
	"\fchecked_expr\x18\x02 \x01(\v2\x15.cel.expr.CheckedExprH\x00R\vcheckedExpr\x12K\n" +
	"\bbindings\x18\x03 \x03(\v2/.cel.expr.conformance.EvalRequest.BindingsEntryR\bbindings\x12\x1c\n" +
	"\tcontainer\x18\x04 \x01(\tR\tcontainer\x1aP\n" +
	"\rBindingsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.cel.expr.ExprValueR\x05value:\x028\x01B\v\n" +
	"\texpr_kind\"g\n" +
	"\fEvalResponse\x12+\n" +
	"\x06result\x18\x01 \x01(\v2\x13.cel.expr.ExprValueR\x06result\x12*\n" +
	"\x06issues\x18\x02 \x01(\v2\x12.cel.expr.ErrorSetR\x06issues\"p\n" +
	"\x0eSourcePosition\x12\x1a\n" +
	"\blocation\x18\x01 \x01(\tR\blocation\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\x12\x12\n" +
	"\x04line\x18\x03 \x01(\x05R\x04line\x12\x16\n" +
	"\x06column\x18\x04 \x01(\x05R\x06column\"\xf8\x01\n" +
	"\fIssueDetails\x12G\n" +
	"\bseverity\x18\x01 \x01(\x0e2+.cel.expr.conformance.IssueDetails.SeverityR\bseverity\x12@\n" +
	"\bposition\x18\x02 \x01(\v2$.cel.expr.conformance.SourcePositionR\bposition\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\x03R\x02id\"M\n" +
	"\bSeverity\x12\x18\n" +
	"\x14SEVERITY_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vDEPRECATION\x10\x01\x12\v\n" +
	"\aWARNING\x10\x02\x12\t\n" +
	"\x05ERROR\x10\x032\x8d\x02\n" +
	"\x12ConformanceService\x12R\n" +
	"\x05Parse\x12\".cel.expr.conformance.ParseRequest\x1a#.cel.expr.conformance.ParseResponse\"\x00\x12R\n" +
	"\x05Check\x12\".cel.expr.conformance.CheckRequest\x1a#.cel.expr.conformance.CheckResponse\"\x00\x12O\n" +
	"\x04Eval\x12!.cel.expr.conformance.EvalRequest\x1a\".cel.expr.conformance.EvalResponse\"\x00BR\n" +
	"\x18dev.cel.expr.conformanceB\x17ConformanceServiceProtoP\x01Z\x18cel.dev/expr/conformance\xf8\x01\x01b\x06proto3"

var (
	file_cel_expr_conformance_conformance_service_proto_rawDescOnce sync.Once
	file_cel_expr_conformance_conformance_service_proto_rawDescData []byte
)

func file_cel_expr_conformance_conformance_service_proto_rawDescGZIP() []byte {
	file_cel_expr_conformance_conformance_service_proto_rawDescOnce.Do(func() {
		file_cel_expr_conformance_conformance_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cel_expr_conformance_conformance_service_proto_rawDesc), len(file_cel_expr_conformance_conformance_service_proto_rawDesc)))
	})
	return file_cel_expr_conformance_conformance_service_proto_rawDescData
}

var file_cel_expr_conformance_conformance_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_cel_expr_conformance_conformance_service_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_cel_expr_conformance_conformance_service_proto_goTypes = []any{
	(IssueDetails_Severity)(0), // 0: cel.expr.conformance.IssueDetails.Severity
	(*ParseRequest)(nil),       // 1: cel.expr.conformance.ParseRequest
	(*ParseResponse)(nil),      // 2: cel.expr.conformance.ParseResponse
	(*CheckRequest)(nil),       // 3: cel.expr.conformance.CheckRequest
	(*CheckResponse)(nil),      // 4: cel.expr.conformance.CheckResponse
	(*EvalRequest)(nil),        // 5: cel.expr.conformance.EvalRequest
	(*EvalResponse)(nil),       // 6: cel.expr.conformance.EvalResponse
	(*SourcePosition)(nil),     // 7: cel.expr.conformance.SourcePosition
	(*IssueDetails)(nil),       // 8: cel.expr.conformance.IssueDetails
	nil,                        // 9: cel.expr.conformance.EvalRequest.BindingsEntry
	(*expr.ParsedExpr)(nil),    // 10: cel.expr.ParsedExpr
	(*expr.ErrorSet)(nil),      // 11: cel.expr.ErrorSet
	(*expr.Decl)(nil),          // 12: cel.expr.Decl
	(*expr.CheckedExpr)(nil),   // 13: cel.expr.CheckedExpr
	(*expr.ExprValue)(nil),     // 14: cel.expr.ExprValue
}
var file_cel_expr_conformance_conformance_service_proto_depIdxs = []int32{
	10, // 0: cel.expr.conformance.ParseResponse.parsed_expr:type_name -> cel.expr.ParsedExpr
	11, // 1: cel.expr.conformance.ParseResponse.issues:type_name -> cel.expr.ErrorSet
	10, // 2: cel.expr.conformance.CheckRequest.parsed_expr:type_name -> cel.expr.ParsedExpr
	12, // 3: cel.expr.conformance.CheckRequest.type_env:type_name -> cel.expr.Decl
	13, // 4: cel.expr.conformance.CheckResponse.checked_expr:type_name -> cel.expr.CheckedExpr
	11, // 5: cel.expr.conformance.CheckResponse.issues:type_name -> cel.expr.ErrorSet
	10, // 6: cel.expr.conformance.EvalRequest.parsed_expr:type_name -> cel.expr.ParsedExpr
	13, // 7: cel.expr.conformance.EvalRequest.checked_expr:type_name -> cel.expr.CheckedExpr
	9,  // 8: cel.expr.conformance.EvalRequest.bindings:type_name -> cel.expr.conformance.EvalRequest.BindingsEntry
	14, // 9: cel.expr.conformance.EvalResponse.result:type_name -> cel.expr.ExprValue
	11, // 10: cel.expr.conformance.EvalResponse.issues:type_name -> cel.expr.ErrorSet
	0,  // 11: cel.expr.conformance.IssueDetails.severity:type_name -> cel.expr.conformance.IssueDetails.Severity
	7,  // 12: cel.expr.conformance.IssueDetails.position:type_name -> cel.expr.conformance.SourcePosition
	14, // 13: cel.expr.conformance.EvalRequest.BindingsEntry.value:type_name -> cel.expr.ExprValue
	1,  // 14: cel.expr.conformance.ConformanceService.Parse:input_type -> cel.expr.conformance.ParseRequest
	3,  // 15: cel.expr.conformance.ConformanceService.Check:input_type -> cel.expr.conformance.CheckRequest
	5,  // 16: cel.expr.conformance.ConformanceService.Eval:input_type -> cel.expr.conformance.EvalRequest
	2,  // 17: cel.expr.conformance.ConformanceService.Parse:output_type -> cel.expr.conformance.ParseResponse
	4,  // 18: cel.expr.conformance.ConformanceService.Check:output_type -> cel.expr.conformance.CheckResponse
	6,  // 19: cel.expr.conformance.ConformanceService.Eval:output_type -> cel.expr.conformance.EvalResponse
	17, // [17:20] is the sub-list for method output_type
	14, // [14:17] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_cel_expr_conformance_conformance_service_proto_init() }
func file_cel_expr_conformance_conformance_service_proto_init() {
	if File_cel_expr_conformance_conformance_service_proto != nil {
		return
	}
	file_cel_expr_conformance_conformance_service_proto_msgTypes[4].OneofWrappers = []any{
		(*EvalRequest_ParsedExpr)(nil),
		(*EvalRequest_CheckedExpr)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cel_expr_conformance_conformance_service_proto_rawDesc), len(file_cel_expr_conformance_conformance_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cel_expr_conformance_conformance_service_proto_goTypes,
		DependencyIndexes: file_cel_expr_conformance_conformance_service_proto_depIdxs,
		EnumInfos:         file_cel_expr_conformance_conformance_service_proto_enumTypes,
		MessageInfos:      file_cel_expr_conformance_conformance_service_proto_msgTypes,
	}.Build()
	File_cel_expr_conformance_conformance_service_proto = out.File
	file_cel_expr_conformance_conformance_service_proto_goTypes = nil
	file_cel_expr_conformance_conformance_service_proto_depIdxs = nil
}
