// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/test/v1/proto2/test_all_types.proto

package test_all_types

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	duration "github.com/golang/protobuf/ptypes/duration"
	_struct "github.com/golang/protobuf/ptypes/struct"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GlobalEnum int32

const (
	GlobalEnum_GOO GlobalEnum = 0
	GlobalEnum_GAR GlobalEnum = 1
	GlobalEnum_GAZ GlobalEnum = 2
)

var GlobalEnum_name = map[int32]string{
	0: "GOO",
	1: "GAR",
	2: "GAZ",
}

var GlobalEnum_value = map[string]int32{
	"GOO": 0,
	"GAR": 1,
	"GAZ": 2,
}

func (x GlobalEnum) Enum() *GlobalEnum {
	p := new(GlobalEnum)
	*p = x
	return p
}

func (x GlobalEnum) String() string {
	return proto.EnumName(GlobalEnum_name, int32(x))
}

func (x *GlobalEnum) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(GlobalEnum_value, data, "GlobalEnum")
	if err != nil {
		return err
	}
	*x = GlobalEnum(value)
	return nil
}

func (GlobalEnum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_98cc99a98b5d98fe, []int{0}
}

type TestAllTypes_NestedEnum int32

const (
	TestAllTypes_FOO TestAllTypes_NestedEnum = 0
	TestAllTypes_BAR TestAllTypes_NestedEnum = 1
	TestAllTypes_BAZ TestAllTypes_NestedEnum = 2
)

var TestAllTypes_NestedEnum_name = map[int32]string{
	0: "FOO",
	1: "BAR",
	2: "BAZ",
}

var TestAllTypes_NestedEnum_value = map[string]int32{
	"FOO": 0,
	"BAR": 1,
	"BAZ": 2,
}

func (x TestAllTypes_NestedEnum) Enum() *TestAllTypes_NestedEnum {
	p := new(TestAllTypes_NestedEnum)
	*p = x
	return p
}

func (x TestAllTypes_NestedEnum) String() string {
	return proto.EnumName(TestAllTypes_NestedEnum_name, int32(x))
}

func (x *TestAllTypes_NestedEnum) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(TestAllTypes_NestedEnum_value, data, "TestAllTypes_NestedEnum")
	if err != nil {
		return err
	}
	*x = TestAllTypes_NestedEnum(value)
	return nil
}

func (TestAllTypes_NestedEnum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_98cc99a98b5d98fe, []int{0, 0}
}

type TestAllTypes struct {
	SingleInt32         *int32                `protobuf:"varint,1,opt,name=single_int32,json=singleInt32,def=-32" json:"single_int32,omitempty"`
	SingleInt64         *int64                `protobuf:"varint,2,opt,name=single_int64,json=singleInt64,def=-64" json:"single_int64,omitempty"`
	SingleUint32        *uint32               `protobuf:"varint,3,opt,name=single_uint32,json=singleUint32,def=32" json:"single_uint32,omitempty"`
	SingleUint64        *uint64               `protobuf:"varint,4,opt,name=single_uint64,json=singleUint64,def=64" json:"single_uint64,omitempty"`
	SingleSint32        *int32                `protobuf:"zigzag32,5,opt,name=single_sint32,json=singleSint32" json:"single_sint32,omitempty"`
	SingleSint64        *int64                `protobuf:"zigzag64,6,opt,name=single_sint64,json=singleSint64" json:"single_sint64,omitempty"`
	SingleFixed32       *uint32               `protobuf:"fixed32,7,opt,name=single_fixed32,json=singleFixed32" json:"single_fixed32,omitempty"`
	SingleFixed64       *uint64               `protobuf:"fixed64,8,opt,name=single_fixed64,json=singleFixed64" json:"single_fixed64,omitempty"`
	SingleSfixed32      *int32                `protobuf:"fixed32,9,opt,name=single_sfixed32,json=singleSfixed32" json:"single_sfixed32,omitempty"`
	SingleSfixed64      *int64                `protobuf:"fixed64,10,opt,name=single_sfixed64,json=singleSfixed64" json:"single_sfixed64,omitempty"`
	SingleFloat         *float32              `protobuf:"fixed32,11,opt,name=single_float,json=singleFloat,def=3" json:"single_float,omitempty"`
	SingleDouble        *float64              `protobuf:"fixed64,12,opt,name=single_double,json=singleDouble,def=6.4" json:"single_double,omitempty"`
	SingleBool          *bool                 `protobuf:"varint,13,opt,name=single_bool,json=singleBool,def=1" json:"single_bool,omitempty"`
	SingleString        *string               `protobuf:"bytes,14,opt,name=single_string,json=singleString,def=empty" json:"single_string,omitempty"`
	SingleBytes         []byte                `protobuf:"bytes,15,opt,name=single_bytes,json=singleBytes,def=none" json:"single_bytes,omitempty"`
	SingleAny           *any.Any              `protobuf:"bytes,100,opt,name=single_any,json=singleAny" json:"single_any,omitempty"`
	SingleDuration      *duration.Duration    `protobuf:"bytes,101,opt,name=single_duration,json=singleDuration" json:"single_duration,omitempty"`
	SingleTimestamp     *timestamp.Timestamp  `protobuf:"bytes,102,opt,name=single_timestamp,json=singleTimestamp" json:"single_timestamp,omitempty"`
	SingleStruct        *_struct.Struct       `protobuf:"bytes,103,opt,name=single_struct,json=singleStruct" json:"single_struct,omitempty"`
	SingleValue         *_struct.Value        `protobuf:"bytes,104,opt,name=single_value,json=singleValue" json:"single_value,omitempty"`
	SingleInt64Wrapper  *wrappers.Int64Value  `protobuf:"bytes,105,opt,name=single_int64_wrapper,json=singleInt64Wrapper" json:"single_int64_wrapper,omitempty"`
	SingleInt32Wrapper  *wrappers.Int32Value  `protobuf:"bytes,106,opt,name=single_int32_wrapper,json=singleInt32Wrapper" json:"single_int32_wrapper,omitempty"`
	SingleDoubleWrapper *wrappers.DoubleValue `protobuf:"bytes,107,opt,name=single_double_wrapper,json=singleDoubleWrapper" json:"single_double_wrapper,omitempty"`
	SingleFloatWrapper  *wrappers.FloatValue  `protobuf:"bytes,108,opt,name=single_float_wrapper,json=singleFloatWrapper" json:"single_float_wrapper,omitempty"`
	SingleUint64Wrapper *wrappers.UInt64Value `protobuf:"bytes,109,opt,name=single_uint64_wrapper,json=singleUint64Wrapper" json:"single_uint64_wrapper,omitempty"`
	SingleUint32Wrapper *wrappers.UInt32Value `protobuf:"bytes,110,opt,name=single_uint32_wrapper,json=singleUint32Wrapper" json:"single_uint32_wrapper,omitempty"`
	SingleStringWrapper *wrappers.StringValue `protobuf:"bytes,111,opt,name=single_string_wrapper,json=singleStringWrapper" json:"single_string_wrapper,omitempty"`
	SingleBoolWrapper   *wrappers.BoolValue   `protobuf:"bytes,112,opt,name=single_bool_wrapper,json=singleBoolWrapper" json:"single_bool_wrapper,omitempty"`
	SingleBytesWrapper  *wrappers.BytesValue  `protobuf:"bytes,113,opt,name=single_bytes_wrapper,json=singleBytesWrapper" json:"single_bytes_wrapper,omitempty"`
	// Types that are valid to be assigned to NestedType:
	//	*TestAllTypes_SingleNestedMessage
	//	*TestAllTypes_SingleNestedEnum
	NestedType            isTestAllTypes_NestedType     `protobuf_oneof:"nested_type"`
	RepeatedInt32         []int32                       `protobuf:"varint,31,rep,name=repeated_int32,json=repeatedInt32" json:"repeated_int32,omitempty"`
	RepeatedInt64         []int64                       `protobuf:"varint,32,rep,name=repeated_int64,json=repeatedInt64" json:"repeated_int64,omitempty"`
	RepeatedUint32        []uint32                      `protobuf:"varint,33,rep,name=repeated_uint32,json=repeatedUint32" json:"repeated_uint32,omitempty"`
	RepeatedUint64        []uint64                      `protobuf:"varint,34,rep,name=repeated_uint64,json=repeatedUint64" json:"repeated_uint64,omitempty"`
	RepeatedSint32        []int32                       `protobuf:"zigzag32,35,rep,name=repeated_sint32,json=repeatedSint32" json:"repeated_sint32,omitempty"`
	RepeatedSint64        []int64                       `protobuf:"zigzag64,36,rep,name=repeated_sint64,json=repeatedSint64" json:"repeated_sint64,omitempty"`
	RepeatedFixed32       []uint32                      `protobuf:"fixed32,37,rep,name=repeated_fixed32,json=repeatedFixed32" json:"repeated_fixed32,omitempty"`
	RepeatedFixed64       []uint64                      `protobuf:"fixed64,38,rep,name=repeated_fixed64,json=repeatedFixed64" json:"repeated_fixed64,omitempty"`
	RepeatedSfixed32      []int32                       `protobuf:"fixed32,39,rep,name=repeated_sfixed32,json=repeatedSfixed32" json:"repeated_sfixed32,omitempty"`
	RepeatedSfixed64      []int64                       `protobuf:"fixed64,40,rep,name=repeated_sfixed64,json=repeatedSfixed64" json:"repeated_sfixed64,omitempty"`
	RepeatedFloat         []float32                     `protobuf:"fixed32,41,rep,name=repeated_float,json=repeatedFloat" json:"repeated_float,omitempty"`
	RepeatedDouble        []float64                     `protobuf:"fixed64,42,rep,name=repeated_double,json=repeatedDouble" json:"repeated_double,omitempty"`
	RepeatedBool          []bool                        `protobuf:"varint,43,rep,name=repeated_bool,json=repeatedBool" json:"repeated_bool,omitempty"`
	RepeatedString        []string                      `protobuf:"bytes,44,rep,name=repeated_string,json=repeatedString" json:"repeated_string,omitempty"`
	RepeatedBytes         [][]byte                      `protobuf:"bytes,45,rep,name=repeated_bytes,json=repeatedBytes" json:"repeated_bytes,omitempty"`
	RepeatedNestedMessage []*TestAllTypes_NestedMessage `protobuf:"bytes,51,rep,name=repeated_nested_message,json=repeatedNestedMessage" json:"repeated_nested_message,omitempty"`
	RepeatedNestedEnum    []TestAllTypes_NestedEnum     `protobuf:"varint,52,rep,name=repeated_nested_enum,json=repeatedNestedEnum,enum=google.api.expr.test.v1.proto2.TestAllTypes_NestedEnum" json:"repeated_nested_enum,omitempty"`
	RepeatedStringPiece   []string                      `protobuf:"bytes,53,rep,name=repeated_string_piece,json=repeatedStringPiece" json:"repeated_string_piece,omitempty"`
	RepeatedCord          []string                      `protobuf:"bytes,54,rep,name=repeated_cord,json=repeatedCord" json:"repeated_cord,omitempty"`
	RepeatedLazyMessage   []*TestAllTypes_NestedMessage `protobuf:"bytes,55,rep,name=repeated_lazy_message,json=repeatedLazyMessage" json:"repeated_lazy_message,omitempty"`
	MapStringString       map[string]string             `protobuf:"bytes,61,rep,name=map_string_string,json=mapStringString" json:"map_string_string,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	MapInt64NestedType    map[int64]*NestedTestAllTypes `protobuf:"bytes,62,rep,name=map_int64_nested_type,json=mapInt64NestedType" json:"map_int64_nested_type,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	XXX_NoUnkeyedLiteral  struct{}                      `json:"-"`
	XXX_unrecognized      []byte                        `json:"-"`
	XXX_sizecache         int32                         `json:"-"`
}

func (m *TestAllTypes) Reset()         { *m = TestAllTypes{} }
func (m *TestAllTypes) String() string { return proto.CompactTextString(m) }
func (*TestAllTypes) ProtoMessage()    {}
func (*TestAllTypes) Descriptor() ([]byte, []int) {
	return fileDescriptor_98cc99a98b5d98fe, []int{0}
}

func (m *TestAllTypes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestAllTypes.Unmarshal(m, b)
}
func (m *TestAllTypes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestAllTypes.Marshal(b, m, deterministic)
}
func (m *TestAllTypes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestAllTypes.Merge(m, src)
}
func (m *TestAllTypes) XXX_Size() int {
	return xxx_messageInfo_TestAllTypes.Size(m)
}
func (m *TestAllTypes) XXX_DiscardUnknown() {
	xxx_messageInfo_TestAllTypes.DiscardUnknown(m)
}

var xxx_messageInfo_TestAllTypes proto.InternalMessageInfo

const Default_TestAllTypes_SingleInt32 int32 = -32
const Default_TestAllTypes_SingleInt64 int64 = -64
const Default_TestAllTypes_SingleUint32 uint32 = 32
const Default_TestAllTypes_SingleUint64 uint64 = 64
const Default_TestAllTypes_SingleFloat float32 = 3
const Default_TestAllTypes_SingleDouble float64 = 6.4
const Default_TestAllTypes_SingleBool bool = true
const Default_TestAllTypes_SingleString string = "empty"

var Default_TestAllTypes_SingleBytes []byte = []byte("none")

const Default_TestAllTypes_SingleNestedEnum TestAllTypes_NestedEnum = TestAllTypes_BAR

func (m *TestAllTypes) GetSingleInt32() int32 {
	if m != nil && m.SingleInt32 != nil {
		return *m.SingleInt32
	}
	return Default_TestAllTypes_SingleInt32
}

func (m *TestAllTypes) GetSingleInt64() int64 {
	if m != nil && m.SingleInt64 != nil {
		return *m.SingleInt64
	}
	return Default_TestAllTypes_SingleInt64
}

func (m *TestAllTypes) GetSingleUint32() uint32 {
	if m != nil && m.SingleUint32 != nil {
		return *m.SingleUint32
	}
	return Default_TestAllTypes_SingleUint32
}

func (m *TestAllTypes) GetSingleUint64() uint64 {
	if m != nil && m.SingleUint64 != nil {
		return *m.SingleUint64
	}
	return Default_TestAllTypes_SingleUint64
}

func (m *TestAllTypes) GetSingleSint32() int32 {
	if m != nil && m.SingleSint32 != nil {
		return *m.SingleSint32
	}
	return 0
}

func (m *TestAllTypes) GetSingleSint64() int64 {
	if m != nil && m.SingleSint64 != nil {
		return *m.SingleSint64
	}
	return 0
}

func (m *TestAllTypes) GetSingleFixed32() uint32 {
	if m != nil && m.SingleFixed32 != nil {
		return *m.SingleFixed32
	}
	return 0
}

func (m *TestAllTypes) GetSingleFixed64() uint64 {
	if m != nil && m.SingleFixed64 != nil {
		return *m.SingleFixed64
	}
	return 0
}

func (m *TestAllTypes) GetSingleSfixed32() int32 {
	if m != nil && m.SingleSfixed32 != nil {
		return *m.SingleSfixed32
	}
	return 0
}

func (m *TestAllTypes) GetSingleSfixed64() int64 {
	if m != nil && m.SingleSfixed64 != nil {
		return *m.SingleSfixed64
	}
	return 0
}

func (m *TestAllTypes) GetSingleFloat() float32 {
	if m != nil && m.SingleFloat != nil {
		return *m.SingleFloat
	}
	return Default_TestAllTypes_SingleFloat
}

func (m *TestAllTypes) GetSingleDouble() float64 {
	if m != nil && m.SingleDouble != nil {
		return *m.SingleDouble
	}
	return Default_TestAllTypes_SingleDouble
}

func (m *TestAllTypes) GetSingleBool() bool {
	if m != nil && m.SingleBool != nil {
		return *m.SingleBool
	}
	return Default_TestAllTypes_SingleBool
}

func (m *TestAllTypes) GetSingleString() string {
	if m != nil && m.SingleString != nil {
		return *m.SingleString
	}
	return Default_TestAllTypes_SingleString
}

func (m *TestAllTypes) GetSingleBytes() []byte {
	if m != nil && m.SingleBytes != nil {
		return m.SingleBytes
	}
	return append([]byte(nil), Default_TestAllTypes_SingleBytes...)
}

func (m *TestAllTypes) GetSingleAny() *any.Any {
	if m != nil {
		return m.SingleAny
	}
	return nil
}

func (m *TestAllTypes) GetSingleDuration() *duration.Duration {
	if m != nil {
		return m.SingleDuration
	}
	return nil
}

func (m *TestAllTypes) GetSingleTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.SingleTimestamp
	}
	return nil
}

func (m *TestAllTypes) GetSingleStruct() *_struct.Struct {
	if m != nil {
		return m.SingleStruct
	}
	return nil
}

func (m *TestAllTypes) GetSingleValue() *_struct.Value {
	if m != nil {
		return m.SingleValue
	}
	return nil
}

func (m *TestAllTypes) GetSingleInt64Wrapper() *wrappers.Int64Value {
	if m != nil {
		return m.SingleInt64Wrapper
	}
	return nil
}

func (m *TestAllTypes) GetSingleInt32Wrapper() *wrappers.Int32Value {
	if m != nil {
		return m.SingleInt32Wrapper
	}
	return nil
}

func (m *TestAllTypes) GetSingleDoubleWrapper() *wrappers.DoubleValue {
	if m != nil {
		return m.SingleDoubleWrapper
	}
	return nil
}

func (m *TestAllTypes) GetSingleFloatWrapper() *wrappers.FloatValue {
	if m != nil {
		return m.SingleFloatWrapper
	}
	return nil
}

func (m *TestAllTypes) GetSingleUint64Wrapper() *wrappers.UInt64Value {
	if m != nil {
		return m.SingleUint64Wrapper
	}
	return nil
}

func (m *TestAllTypes) GetSingleUint32Wrapper() *wrappers.UInt32Value {
	if m != nil {
		return m.SingleUint32Wrapper
	}
	return nil
}

func (m *TestAllTypes) GetSingleStringWrapper() *wrappers.StringValue {
	if m != nil {
		return m.SingleStringWrapper
	}
	return nil
}

func (m *TestAllTypes) GetSingleBoolWrapper() *wrappers.BoolValue {
	if m != nil {
		return m.SingleBoolWrapper
	}
	return nil
}

func (m *TestAllTypes) GetSingleBytesWrapper() *wrappers.BytesValue {
	if m != nil {
		return m.SingleBytesWrapper
	}
	return nil
}

type isTestAllTypes_NestedType interface {
	isTestAllTypes_NestedType()
}

type TestAllTypes_SingleNestedMessage struct {
	SingleNestedMessage *TestAllTypes_NestedMessage `protobuf:"bytes,21,opt,name=single_nested_message,json=singleNestedMessage,oneof"`
}

type TestAllTypes_SingleNestedEnum struct {
	SingleNestedEnum TestAllTypes_NestedEnum `protobuf:"varint,22,opt,name=single_nested_enum,json=singleNestedEnum,enum=google.api.expr.test.v1.proto2.TestAllTypes_NestedEnum,oneof,def=1"`
}

func (*TestAllTypes_SingleNestedMessage) isTestAllTypes_NestedType() {}

func (*TestAllTypes_SingleNestedEnum) isTestAllTypes_NestedType() {}

func (m *TestAllTypes) GetNestedType() isTestAllTypes_NestedType {
	if m != nil {
		return m.NestedType
	}
	return nil
}

func (m *TestAllTypes) GetSingleNestedMessage() *TestAllTypes_NestedMessage {
	if x, ok := m.GetNestedType().(*TestAllTypes_SingleNestedMessage); ok {
		return x.SingleNestedMessage
	}
	return nil
}

func (m *TestAllTypes) GetSingleNestedEnum() TestAllTypes_NestedEnum {
	if x, ok := m.GetNestedType().(*TestAllTypes_SingleNestedEnum); ok {
		return x.SingleNestedEnum
	}
	return Default_TestAllTypes_SingleNestedEnum
}

func (m *TestAllTypes) GetRepeatedInt32() []int32 {
	if m != nil {
		return m.RepeatedInt32
	}
	return nil
}

func (m *TestAllTypes) GetRepeatedInt64() []int64 {
	if m != nil {
		return m.RepeatedInt64
	}
	return nil
}

func (m *TestAllTypes) GetRepeatedUint32() []uint32 {
	if m != nil {
		return m.RepeatedUint32
	}
	return nil
}

func (m *TestAllTypes) GetRepeatedUint64() []uint64 {
	if m != nil {
		return m.RepeatedUint64
	}
	return nil
}

func (m *TestAllTypes) GetRepeatedSint32() []int32 {
	if m != nil {
		return m.RepeatedSint32
	}
	return nil
}

func (m *TestAllTypes) GetRepeatedSint64() []int64 {
	if m != nil {
		return m.RepeatedSint64
	}
	return nil
}

func (m *TestAllTypes) GetRepeatedFixed32() []uint32 {
	if m != nil {
		return m.RepeatedFixed32
	}
	return nil
}

func (m *TestAllTypes) GetRepeatedFixed64() []uint64 {
	if m != nil {
		return m.RepeatedFixed64
	}
	return nil
}

func (m *TestAllTypes) GetRepeatedSfixed32() []int32 {
	if m != nil {
		return m.RepeatedSfixed32
	}
	return nil
}

func (m *TestAllTypes) GetRepeatedSfixed64() []int64 {
	if m != nil {
		return m.RepeatedSfixed64
	}
	return nil
}

func (m *TestAllTypes) GetRepeatedFloat() []float32 {
	if m != nil {
		return m.RepeatedFloat
	}
	return nil
}

func (m *TestAllTypes) GetRepeatedDouble() []float64 {
	if m != nil {
		return m.RepeatedDouble
	}
	return nil
}

func (m *TestAllTypes) GetRepeatedBool() []bool {
	if m != nil {
		return m.RepeatedBool
	}
	return nil
}

func (m *TestAllTypes) GetRepeatedString() []string {
	if m != nil {
		return m.RepeatedString
	}
	return nil
}

func (m *TestAllTypes) GetRepeatedBytes() [][]byte {
	if m != nil {
		return m.RepeatedBytes
	}
	return nil
}

func (m *TestAllTypes) GetRepeatedNestedMessage() []*TestAllTypes_NestedMessage {
	if m != nil {
		return m.RepeatedNestedMessage
	}
	return nil
}

func (m *TestAllTypes) GetRepeatedNestedEnum() []TestAllTypes_NestedEnum {
	if m != nil {
		return m.RepeatedNestedEnum
	}
	return nil
}

func (m *TestAllTypes) GetRepeatedStringPiece() []string {
	if m != nil {
		return m.RepeatedStringPiece
	}
	return nil
}

func (m *TestAllTypes) GetRepeatedCord() []string {
	if m != nil {
		return m.RepeatedCord
	}
	return nil
}

func (m *TestAllTypes) GetRepeatedLazyMessage() []*TestAllTypes_NestedMessage {
	if m != nil {
		return m.RepeatedLazyMessage
	}
	return nil
}

func (m *TestAllTypes) GetMapStringString() map[string]string {
	if m != nil {
		return m.MapStringString
	}
	return nil
}

func (m *TestAllTypes) GetMapInt64NestedType() map[int64]*NestedTestAllTypes {
	if m != nil {
		return m.MapInt64NestedType
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*TestAllTypes) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*TestAllTypes_SingleNestedMessage)(nil),
		(*TestAllTypes_SingleNestedEnum)(nil),
	}
}

type TestAllTypes_NestedMessage struct {
	Bb                   *int32   `protobuf:"varint,1,opt,name=bb" json:"bb,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestAllTypes_NestedMessage) Reset()         { *m = TestAllTypes_NestedMessage{} }
func (m *TestAllTypes_NestedMessage) String() string { return proto.CompactTextString(m) }
func (*TestAllTypes_NestedMessage) ProtoMessage()    {}
func (*TestAllTypes_NestedMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_98cc99a98b5d98fe, []int{0, 0}
}

func (m *TestAllTypes_NestedMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestAllTypes_NestedMessage.Unmarshal(m, b)
}
func (m *TestAllTypes_NestedMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestAllTypes_NestedMessage.Marshal(b, m, deterministic)
}
func (m *TestAllTypes_NestedMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestAllTypes_NestedMessage.Merge(m, src)
}
func (m *TestAllTypes_NestedMessage) XXX_Size() int {
	return xxx_messageInfo_TestAllTypes_NestedMessage.Size(m)
}
func (m *TestAllTypes_NestedMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_TestAllTypes_NestedMessage.DiscardUnknown(m)
}

var xxx_messageInfo_TestAllTypes_NestedMessage proto.InternalMessageInfo

func (m *TestAllTypes_NestedMessage) GetBb() int32 {
	if m != nil && m.Bb != nil {
		return *m.Bb
	}
	return 0
}

type NestedTestAllTypes struct {
	Child                *NestedTestAllTypes `protobuf:"bytes,1,opt,name=child" json:"child,omitempty"`
	Payload              *TestAllTypes       `protobuf:"bytes,2,opt,name=payload" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *NestedTestAllTypes) Reset()         { *m = NestedTestAllTypes{} }
func (m *NestedTestAllTypes) String() string { return proto.CompactTextString(m) }
func (*NestedTestAllTypes) ProtoMessage()    {}
func (*NestedTestAllTypes) Descriptor() ([]byte, []int) {
	return fileDescriptor_98cc99a98b5d98fe, []int{1}
}

func (m *NestedTestAllTypes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NestedTestAllTypes.Unmarshal(m, b)
}
func (m *NestedTestAllTypes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NestedTestAllTypes.Marshal(b, m, deterministic)
}
func (m *NestedTestAllTypes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NestedTestAllTypes.Merge(m, src)
}
func (m *NestedTestAllTypes) XXX_Size() int {
	return xxx_messageInfo_NestedTestAllTypes.Size(m)
}
func (m *NestedTestAllTypes) XXX_DiscardUnknown() {
	xxx_messageInfo_NestedTestAllTypes.DiscardUnknown(m)
}

var xxx_messageInfo_NestedTestAllTypes proto.InternalMessageInfo

func (m *NestedTestAllTypes) GetChild() *NestedTestAllTypes {
	if m != nil {
		return m.Child
	}
	return nil
}

func (m *NestedTestAllTypes) GetPayload() *TestAllTypes {
	if m != nil {
		return m.Payload
	}
	return nil
}

func init() {
	proto.RegisterEnum("google.api.expr.test.v1.proto2.GlobalEnum", GlobalEnum_name, GlobalEnum_value)
	proto.RegisterEnum("google.api.expr.test.v1.proto2.TestAllTypes_NestedEnum", TestAllTypes_NestedEnum_name, TestAllTypes_NestedEnum_value)
	proto.RegisterType((*TestAllTypes)(nil), "google.api.expr.test.v1.proto2.TestAllTypes")
	proto.RegisterMapType((map[int64]*NestedTestAllTypes)(nil), "google.api.expr.test.v1.proto2.TestAllTypes.MapInt64NestedTypeEntry")
	proto.RegisterMapType((map[string]string)(nil), "google.api.expr.test.v1.proto2.TestAllTypes.MapStringStringEntry")
	proto.RegisterType((*TestAllTypes_NestedMessage)(nil), "google.api.expr.test.v1.proto2.TestAllTypes.NestedMessage")
	proto.RegisterType((*NestedTestAllTypes)(nil), "google.api.expr.test.v1.proto2.NestedTestAllTypes")
}

func init() {
	proto.RegisterFile("proto/test/v1/proto2/test_all_types.proto", fileDescriptor_98cc99a98b5d98fe)
}

var fileDescriptor_98cc99a98b5d98fe = []byte{
	// 1338 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x57, 0x6b, 0x73, 0xd3, 0x46,
	0x17, 0x66, 0xbd, 0x09, 0x49, 0x36, 0x71, 0xe2, 0x6c, 0x12, 0x58, 0xfc, 0x32, 0xb0, 0x6f, 0xb8,
	0x64, 0xb9, 0xc4, 0x19, 0x6c, 0xbd, 0x82, 0xd7, 0xd3, 0x76, 0x26, 0x2e, 0x24, 0xb4, 0x53, 0x0a,
	0xa3, 0x40, 0x3b, 0xc3, 0x17, 0x8f, 0x6c, 0x6f, 0x8c, 0x8b, 0x2c, 0xa9, 0xb2, 0x04, 0x88, 0x1f,
	0xd4, 0x1f, 0xd7, 0x5f, 0xd1, 0xd1, 0xde, 0xac, 0x0b, 0xa6, 0x03, 0x7c, 0xc9, 0x58, 0xe7, 0x3c,
	0xe7, 0x39, 0xe7, 0x3c, 0xbb, 0x47, 0x27, 0x42, 0x77, 0xc2, 0x28, 0x88, 0x83, 0xa3, 0x98, 0xcf,
	0xe2, 0xa3, 0x77, 0x0f, 0x8e, 0xc4, 0x53, 0x5b, 0x3c, 0xf6, 0x5d, 0xcf, 0xeb, 0xc7, 0x69, 0xc8,
	0x67, 0x2d, 0x61, 0xc5, 0xd7, 0xc6, 0x41, 0x30, 0xf6, 0x78, 0xcb, 0x0d, 0x27, 0x2d, 0xfe, 0x21,
	0x8c, 0x5a, 0x19, 0xaa, 0xf5, 0xee, 0x81, 0x74, 0xb7, 0x9b, 0x57, 0xa4, 0x5f, 0x72, 0x0c, 0x92,
	0xf3, 0x23, 0xd7, 0x4f, 0xa5, 0xaf, 0x79, 0xad, 0xec, 0x1a, 0x25, 0x91, 0x1b, 0x4f, 0x02, 0x5f,
	0xf9, 0xaf, 0x96, 0xfd, 0xb3, 0x38, 0x4a, 0x86, 0xb1, 0xf2, 0x5e, 0x2f, 0x7b, 0xe3, 0xc9, 0x94,
	0xcf, 0x62, 0x77, 0x1a, 0x2e, 0xa2, 0x7f, 0x1f, 0xb9, 0x61, 0xc8, 0x23, 0x55, 0xf9, 0xfe, 0xdf,
	0x4d, 0xb4, 0xf1, 0x92, 0xcf, 0xe2, 0x63, 0xcf, 0x7b, 0x99, 0x35, 0x84, 0x6f, 0xa3, 0x8d, 0xd9,
	0xc4, 0x1f, 0x7b, 0xbc, 0x3f, 0xf1, 0xe3, 0x4e, 0x9b, 0x00, 0x0a, 0xd8, 0x72, 0x17, 0x1e, 0x76,
	0xda, 0xce, 0xba, 0x74, 0xfc, 0x94, 0xd9, 0x8b, 0x38, 0xdb, 0x22, 0x35, 0x0a, 0x18, 0xec, 0xc2,
	0x43, 0xdb, 0xca, 0xe1, 0x6c, 0x0b, 0x1f, 0xa0, 0xba, 0xc2, 0x25, 0x92, 0x10, 0x52, 0xc0, 0xea,
	0xdd, 0x5a, 0xa7, 0xed, 0x28, 0x82, 0x57, 0xc2, 0x5e, 0x02, 0xda, 0x16, 0x59, 0xa2, 0x80, 0x2d,
	0x75, 0x6b, 0xb6, 0x95, 0x07, 0xda, 0x16, 0xbe, 0x61, 0x80, 0x33, 0xc9, 0xb8, 0x4c, 0x01, 0xdb,
	0xd6, 0xa0, 0x33, 0xc9, 0x56, 0x04, 0xd9, 0x16, 0xb9, 0x48, 0x01, 0xc3, 0x79, 0x90, 0x6d, 0xe1,
	0x5b, 0x68, 0x53, 0x81, 0xce, 0x27, 0x1f, 0xf8, 0xa8, 0xd3, 0x26, 0x2b, 0x14, 0xb0, 0x15, 0x47,
	0x85, 0x9e, 0x48, 0x63, 0x19, 0x66, 0x5b, 0x64, 0x95, 0x02, 0x76, 0xb1, 0x00, 0x13, 0x9d, 0x6e,
	0xe9, 0x94, 0x9a, 0x6e, 0x8d, 0x02, 0xb6, 0xe5, 0xa8, 0xe8, 0x33, 0x65, 0xad, 0x00, 0x6d, 0x8b,
	0x20, 0x0a, 0x58, 0xa3, 0x08, 0xb4, 0x2d, 0x7c, 0xd3, 0x68, 0x7c, 0xee, 0x05, 0x6e, 0x4c, 0xd6,
	0x29, 0x60, 0xb5, 0x2e, 0xe8, 0x68, 0x85, 0x4f, 0x32, 0x2b, 0x66, 0xa6, 0xd5, 0x51, 0x90, 0x0c,
	0x3c, 0x4e, 0x36, 0x28, 0x60, 0xa0, 0x0b, 0xed, 0x96, 0x51, 0xee, 0xb1, 0x70, 0xe0, 0x5b, 0x48,
	0x05, 0xf6, 0x07, 0x41, 0xe0, 0x91, 0x3a, 0x05, 0x6c, 0xb5, 0xbb, 0x14, 0x47, 0x09, 0x77, 0x90,
	0x74, 0xf4, 0x82, 0xc0, 0xc3, 0x77, 0xe7, 0xda, 0xc5, 0xd1, 0xc4, 0x1f, 0x93, 0x4d, 0x0a, 0xd8,
	0x5a, 0x77, 0x99, 0x4f, 0xc3, 0x38, 0x35, 0x12, 0x0a, 0x17, 0x3e, 0x30, 0x25, 0x0e, 0xd2, 0x98,
	0xcf, 0xc8, 0x16, 0x05, 0x6c, 0xa3, 0xbb, 0xe4, 0x07, 0x3e, 0xd7, 0x55, 0xf6, 0x32, 0x07, 0xee,
	0x20, 0x95, 0xa2, 0xef, 0xfa, 0x29, 0x19, 0x51, 0xc0, 0xd6, 0xdb, 0xbb, 0x2d, 0x35, 0x37, 0xfa,
	0x76, 0xb6, 0x8e, 0xfd, 0xd4, 0x59, 0x93, 0xb8, 0x63, 0x3f, 0xc5, 0x3d, 0xa3, 0x94, 0x9e, 0x0a,
	0xc2, 0x45, 0xe4, 0x95, 0x4a, 0xe4, 0x63, 0x05, 0xd0, 0x22, 0xea, 0x67, 0xfc, 0x04, 0x35, 0x14,
	0x87, 0x99, 0x0d, 0x72, 0x2e, 0x48, 0x9a, 0x15, 0x92, 0x97, 0x1a, 0xe1, 0xa8, 0xbc, 0xc6, 0x80,
	0xbf, 0xcb, 0x8b, 0x92, 0x0c, 0x63, 0x32, 0x16, 0x1c, 0x97, 0x2b, 0x1c, 0x67, 0xc2, 0x9d, 0x93,
	0x29, 0x19, 0xc6, 0xf8, 0xff, 0x46, 0xa6, 0x77, 0xae, 0x97, 0x70, 0xf2, 0x46, 0x04, 0x5f, 0xaa,
	0x04, 0xff, 0x96, 0x79, 0xb5, 0x70, 0xe2, 0x01, 0x3f, 0x43, 0xbb, 0xf9, 0x41, 0xeb, 0xab, 0x01,
	0x26, 0x13, 0x41, 0xf1, 0x9f, 0x0a, 0x85, 0x18, 0x3b, 0xc9, 0x83, 0x73, 0x83, 0xf8, 0xbb, 0x0c,
	0x2b, 0xd2, 0x75, 0xda, 0x86, 0xee, 0x8f, 0xc5, 0x74, 0x9d, 0x76, 0x99, 0xae, 0xd3, 0xd6, 0x74,
	0x2f, 0xd0, 0x5e, 0xe1, 0xf2, 0x19, 0xbe, 0xb7, 0x82, 0xef, 0x6a, 0xf5, 0x9c, 0x04, 0x4c, 0x12,
	0xee, 0xe4, 0x6f, 0x67, 0xb5, 0x40, 0x71, 0xe9, 0x0d, 0xa1, 0xb7, 0xa0, 0x40, 0x31, 0x04, 0x85,
	0x02, 0x85, 0xa5, 0x5a, 0x60, 0x52, 0xd4, 0x6f, 0xba, 0xa0, 0xc0, 0x57, 0x39, 0x01, 0x77, 0xf2,
	0x2f, 0x9e, 0x4f, 0x33, 0xe6, 0x24, 0xf4, 0x3f, 0xc3, 0xa8, 0x35, 0xdc, 0xc9, 0xbf, 0xf3, 0xaa,
	0x8c, 0x72, 0xe0, 0x0c, 0x63, 0xb0, 0x80, 0x51, 0x0e, 0x5f, 0x81, 0x51, 0x9a, 0x34, 0xe3, 0xcf,
	0x68, 0x27, 0x37, 0xe9, 0x86, 0x2f, 0x5c, 0x70, 0xef, 0xb3, 0xb1, 0x97, 0x6c, 0xdb, 0xf3, 0xf7,
	0x40, 0xf5, 0x40, 0xc4, 0x88, 0x1b, 0xb2, 0x3f, 0x17, 0x1c, 0x88, 0x98, 0xf7, 0xc2, 0x81, 0x08,
	0x8b, 0xa6, 0x0b, 0x4d, 0xb3, 0x3e, 0x9f, 0xc5, 0x7c, 0xd4, 0x9f, 0xf2, 0xd9, 0xcc, 0x1d, 0x73,
	0xb2, 0x27, 0xf8, 0xba, 0xad, 0xcf, 0xef, 0xd2, 0x56, 0x7e, 0x5b, 0xb5, 0x7e, 0x15, 0x14, 0xcf,
	0x24, 0xc3, 0xd3, 0x0b, 0x5a, 0x8c, 0x82, 0x19, 0x7b, 0x08, 0x17, 0x33, 0x72, 0x3f, 0x99, 0x92,
	0x4b, 0x14, 0xb0, 0xcd, 0xf6, 0xc3, 0xaf, 0x48, 0xf7, 0xc4, 0x4f, 0xa6, 0x5d, 0xd8, 0x3b, 0x76,
	0x9e, 0x5e, 0x70, 0x1a, 0xf9, 0x84, 0x99, 0x23, 0xdb, 0x16, 0x11, 0x0f, 0xb9, 0x9b, 0x25, 0x92,
	0xfb, 0xe9, 0x3a, 0x85, 0x6c, 0xd9, 0xa9, 0x6b, 0xab, 0xdc, 0x9f, 0x25, 0x98, 0x6d, 0x11, 0x4a,
	0x21, 0x83, 0x05, 0x98, 0x5c, 0x2a, 0x06, 0xa6, 0x16, 0xe8, 0x7f, 0x29, 0x64, 0x75, 0xc7, 0x44,
	0x9b, 0xf5, 0x59, 0x04, 0xda, 0x16, 0xd9, 0xa7, 0x90, 0x2d, 0x15, 0x81, 0x25, 0x46, 0xb5, 0x40,
	0x6f, 0x50, 0xc8, 0xb6, 0xe7, 0xc0, 0xb3, 0x2a, 0xa3, 0x5a, 0xa2, 0x37, 0x29, 0x64, 0xb8, 0x08,
	0xb4, 0x2d, 0x7c, 0x07, 0x35, 0x0c, 0x50, 0x6f, 0xbe, 0x5b, 0x14, 0xb2, 0x15, 0xc7, 0x10, 0xe8,
	0x55, 0x5a, 0x81, 0xda, 0x16, 0xb9, 0x4d, 0x21, 0xbb, 0x58, 0x82, 0xda, 0x16, 0xbe, 0x87, 0xb6,
	0xe7, 0xe9, 0x35, 0xed, 0x01, 0x85, 0x6c, 0xcb, 0x31, 0x1c, 0x66, 0xa5, 0x56, 0xc1, 0xb6, 0x45,
	0x18, 0x85, 0xac, 0x51, 0x06, 0xcb, 0xb5, 0x3f, 0x2f, 0x42, 0x2c, 0xd6, 0x3b, 0x14, 0xb2, 0xda,
	0x5c, 0x7a, 0xb9, 0x57, 0xf3, 0xfd, 0xab, 0xcd, 0x7a, 0x97, 0x42, 0x06, 0xe6, 0xfd, 0xab, 0xb5,
	0x7a, 0x03, 0x99, 0x48, 0xb9, 0x58, 0xef, 0x51, 0xc8, 0x56, 0x9d, 0x0d, 0x6d, 0x14, 0x4b, 0xb5,
	0xa0, 0xa6, 0x5c, 0xab, 0xf7, 0x29, 0x64, 0x6b, 0x39, 0x35, 0xe5, 0x46, 0xcd, 0x57, 0x27, 0x77,
	0xea, 0x21, 0x85, 0x6c, 0x63, 0x5e, 0x9d, 0xdc, 0xa7, 0x11, 0xba, 0x6c, 0x60, 0xa5, 0x41, 0xea,
	0x50, 0xf8, 0x6d, 0x83, 0xe4, 0xec, 0x69, 0xea, 0xe2, 0x20, 0x4d, 0xd0, 0x6e, 0x39, 0xa7, 0x18,
	0x25, 0x8b, 0xc2, 0x6f, 0x18, 0x25, 0x07, 0x17, 0xb3, 0x89, 0x29, 0xb2, 0xd1, 0x5e, 0x49, 0xae,
	0x7e, 0x38, 0xe1, 0x43, 0x4e, 0xfe, 0x97, 0x89, 0xd6, 0xab, 0xad, 0xd6, 0x9c, 0x9d, 0xa2, 0x70,
	0x2f, 0x32, 0x77, 0xf6, 0x5f, 0xa4, 0x89, 0x1b, 0x06, 0xd1, 0x88, 0xd8, 0x0a, 0x0f, 0xe6, 0xe7,
	0xf1, 0x63, 0x10, 0x8d, 0x70, 0x94, 0x4b, 0xe0, 0xb9, 0x1f, 0x53, 0xa3, 0xde, 0xc3, 0x6f, 0x55,
	0xaf, 0x57, 0x63, 0x60, 0x5e, 0xdc, 0x2f, 0xee, 0xc7, 0x54, 0xeb, 0x37, 0x45, 0xdb, 0x53, 0x37,
	0xd4, 0xfd, 0xa8, 0x5b, 0xf0, 0xbd, 0xc8, 0x77, 0xfc, 0x45, 0xf9, 0x9e, 0xb9, 0xa1, 0x6c, 0x5a,
	0xfe, 0x7d, 0xe2, 0xc7, 0x51, 0xea, 0x6c, 0x4d, 0x8b, 0x56, 0xfc, 0x1e, 0xed, 0x65, 0xe9, 0xe4,
	0xda, 0x53, 0xe7, 0x95, 0x7d, 0xb5, 0x90, 0x1f, 0x44, 0xca, 0xc7, 0x5f, 0x9a, 0x52, 0xbc, 0x91,
	0x64, 0xab, 0x99, 0x4d, 0x66, 0xc5, 0xd3, 0x8a, 0xa3, 0x79, 0x1d, 0xd5, 0x8b, 0x17, 0x67, 0x13,
	0xd5, 0x06, 0x03, 0xf9, 0x29, 0xe1, 0xd4, 0x06, 0x83, 0x66, 0x0f, 0xed, 0x7e, 0xaa, 0x05, 0xdc,
	0x40, 0xf0, 0x2d, 0x4f, 0x05, 0x70, 0xcd, 0xc9, 0x7e, 0xe2, 0x5d, 0xb4, 0x2c, 0xff, 0x63, 0xaa,
	0x09, 0x9b, 0x7c, 0xe8, 0xd6, 0x1e, 0x81, 0x66, 0x8a, 0x2e, 0x2f, 0xa8, 0x29, 0x4f, 0x03, 0x25,
	0xcd, 0xd3, 0x3c, 0xcd, 0x7a, 0xbb, 0xfd, 0x6f, 0xad, 0x2b, 0xc6, 0x9c, 0x00, 0xb9, 0xd4, 0xfb,
	0x07, 0x08, 0xe5, 0xae, 0xea, 0x0a, 0x82, 0x27, 0xcf, 0x9f, 0x37, 0x2e, 0x64, 0x3f, 0x7a, 0xc7,
	0x4e, 0x03, 0xc8, 0x1f, 0xaf, 0x1b, 0xb5, 0x5e, 0x1d, 0xad, 0xe7, 0x74, 0xdf, 0xff, 0x0b, 0x20,
	0x5c, 0x65, 0xce, 0x8a, 0x1b, 0xbe, 0x99, 0x78, 0x23, 0x51, 0xf0, 0x57, 0x16, 0x27, 0x08, 0xf0,
	0x09, 0x5a, 0x09, 0xdd, 0xd4, 0x0b, 0xdc, 0x91, 0x6a, 0xf4, 0xfe, 0x97, 0x9c, 0xb1, 0xa3, 0x83,
	0xef, 0x1e, 0x20, 0x74, 0xea, 0x05, 0x03, 0xd7, 0xd3, 0x0d, 0x9e, 0xea, 0x06, 0x4f, 0x75, 0x83,
	0xa7, 0xa2, 0xc1, 0xee, 0xeb, 0x47, 0xe3, 0x49, 0xfc, 0x26, 0x19, 0xb4, 0x86, 0xc1, 0xf4, 0x48,
	0x7d, 0x6b, 0x0e, 0xb9, 0x77, 0x38, 0x0b, 0xf9, 0xf0, 0xf3, 0x9f, 0xce, 0xff, 0x04, 0x00, 0x00,
	0xff, 0xff, 0x8a, 0xfb, 0x6f, 0x8d, 0x60, 0x0f, 0x00, 0x00,
}
