// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/test/v1/envcheck.proto

package google_api_expr_test_v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	v1alpha1 "google.golang.org/genproto/googleapis/api/expr/v1alpha1"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Env struct {
	Name                 string           `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Decl                 []*v1alpha1.Decl `protobuf:"bytes,2,rep,name=decl,proto3" json:"decl,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Env) Reset()         { *m = Env{} }
func (m *Env) String() string { return proto.CompactTextString(m) }
func (*Env) ProtoMessage()    {}
func (*Env) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd88f4d86742eb7c, []int{0}
}

func (m *Env) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Env.Unmarshal(m, b)
}
func (m *Env) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Env.Marshal(b, m, deterministic)
}
func (m *Env) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Env.Merge(m, src)
}
func (m *Env) XXX_Size() int {
	return xxx_messageInfo_Env.Size(m)
}
func (m *Env) XXX_DiscardUnknown() {
	xxx_messageInfo_Env.DiscardUnknown(m)
}

var xxx_messageInfo_Env proto.InternalMessageInfo

func (m *Env) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Env) GetDecl() []*v1alpha1.Decl {
	if m != nil {
		return m.Decl
	}
	return nil
}

func init() {
	proto.RegisterType((*Env)(nil), "google.api.expr.test.v1.Env")
}

func init() { proto.RegisterFile("proto/test/v1/envcheck.proto", fileDescriptor_cd88f4d86742eb7c) }

var fileDescriptor_cd88f4d86742eb7c = []byte{
	// 159 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x29, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x2f, 0x49, 0x2d, 0x2e, 0xd1, 0x2f, 0x33, 0xd4, 0x4f, 0xcd, 0x2b, 0x4b, 0xce, 0x48,
	0x4d, 0xce, 0xd6, 0x03, 0x0b, 0x0b, 0x89, 0xa7, 0xe7, 0xe7, 0xa7, 0xe7, 0xa4, 0xea, 0x25, 0x16,
	0x64, 0xea, 0xa5, 0x56, 0x14, 0x14, 0xe9, 0x81, 0xd4, 0xe9, 0x95, 0x19, 0x4a, 0xa9, 0x41, 0x24,
	0xf4, 0x13, 0x0b, 0x32, 0xf5, 0x41, 0x12, 0xfa, 0x65, 0x86, 0x89, 0x39, 0x05, 0x19, 0x89, 0x86,
	0xfa, 0x60, 0xed, 0xa9, 0x29, 0x10, 0x03, 0x94, 0x7c, 0xb9, 0x98, 0x5d, 0xf3, 0xca, 0x84, 0x84,
	0xb8, 0x58, 0xf2, 0x12, 0x73, 0x53, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0xc0, 0x6c, 0x21,
	0x23, 0x2e, 0x96, 0x94, 0xd4, 0xe4, 0x1c, 0x09, 0x26, 0x05, 0x66, 0x0d, 0x6e, 0x23, 0x39, 0x3d,
	0x74, 0xab, 0x60, 0x26, 0xea, 0xb9, 0xa4, 0x26, 0xe7, 0x04, 0x81, 0xd5, 0x26, 0xb1, 0x81, 0x4d,
	0x35, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x89, 0x3f, 0x4c, 0x00, 0xb6, 0x00, 0x00, 0x00,
}
